### ISSUE TITLE
DELETE batch/v1 response is not deserializable to io.kubernetes.client.openapi.models.V1Status

### ISSUE THREAD

**Issue by vcsomor** [kubernetes-client/java#880] opened 2020-03-10 12:10 UTC
Using the following versions of the components:
- JDK 1.8
- Java driver:
```xml
        <dependency>
            <groupId>io.kubernetes</groupId>
            <artifactId>client-java</artifactId>
            <version>7.0.0</version>
        </dependency>
```
- Kubernetes:
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
```

The example java code:
```java
    public static void main(String[] args) throws IOException, ApiException {
        final ApiClient client = Config.defaultClient();
        final String rnd = UUID.randomUUID()
                               .toString();

        final V1Container container = new V1Container().name("curl-" + rnd)
                                                       .image("tutum/curl")
                                                       .command(asList("sleep", "5"));

        final V1PodSpec podSpec = new V1PodSpec().restartPolicy("Never")
                                                 .containers(singletonList(container));

        final V1Job jobSpec = new V1Job().apiVersion("batch/v1")
                                         .kind("Job")
                                         .metadata(new V1ObjectMeta().name("curl-job" + rnd)
                                                                     .labels(new HashMap<String, String>() {{
                                                                         put("my-job", "true");
                                                                         put("my-job-id", rnd);
                                                                     }}))
                                         .spec(new V1JobSpec().template(new V1PodTemplateSpec().spec(podSpec)));

        final BatchV1Api batchV1Api = new BatchV1Api(client);
        final V1Job job = batchV1Api.createNamespacedJob("default",
                                                         jobSpec,
                                                         "true",
                                                         null,
                                                         "my-entity");
  
        // wait job to finish
        final BatchV1Api batchV1ApiDelete = new BatchV1Api(client);

		// this call throws an exception see below
        batchV1ApiDelete.deleteNamespacedJob(job.getMetadata().getName(),
                                           "default",
                                           "true",
                                           null,
                                           null,
                                           null,
                                           null,
                                           new V1DeleteOptions().gracePeriodSeconds(300L)
                                                                .orphanDependents(true));
																
	}
```

**When calling the `batchV1ApiDelete.deleteNamespacedJob` then it throws an expcetion because it is expecting the `io.kubernetes.client.openapi.models.V1Status#status` field to be a `String` but got a JSON Object.**

Stacktrace
```
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 65 column 14 path $.status
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:224)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:852)
	at com.google.gson.Gson.fromJson(Gson.java:801)
	at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:139)
	at io.kubernetes.client.openapi.ApiClient.deserialize(ApiClient.java:765)
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:968)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
	at io.kubernetes.client.openapi.apis.BatchV1Api.deleteNamespacedJobWithHttpInfo(BatchV1Api.java:581)
	at io.kubernetes.client.openapi.apis.BatchV1Api.deleteNamespacedJob(BatchV1Api.java:553)
```

Endpoint called:
```
https://localhost:8443/apis/batch/v1/namespaces/default/jobs/curl-job08f8a5bf-3cf4-47b5-b5de-685f8cfe0d01?pretty=true
```

Raw response:
```json
{
   "kind":"Job",
   "apiVersion":"batch/v1",
   "metadata":{
      "name":"curl-job08f8a5bf-3cf4-47b5-b5de-685f8cfe0d01",
      "namespace":"default",
      "selfLink":"/apis/batch/v1/namespaces/default/jobs/curl-job08f8a5bf-3cf4-47b5-b5de-685f8cfe0d01",
      "uid":"9d798b7a-ed82-4159-80fc-7aa54923a6a7",
      "resourceVersion":"529314",
      "creationTimestamp":"2020-03-10T12:06:31Z",
      "deletionTimestamp":"2020-03-10T12:06:52Z",
      "deletionGracePeriodSeconds":0,
      "labels":{
         "my-job":"true",
         "my-job-id":"08f8a5bf-3cf4-47b5-b5de-685f8cfe0d01"
      },
      "finalizers":[
         "orphan"
      ]
   },
   "spec":{
      "parallelism":1,
      "completions":1,
      "backoffLimit":6,
      "selector":{
         "matchLabels":{
            "controller-uid":"9d798b7a-ed82-4159-80fc-7aa54923a6a7"
         }
      },
      "template":{
         "metadata":{
            "creationTimestamp":null,
            "labels":{
               "controller-uid":"9d798b7a-ed82-4159-80fc-7aa54923a6a7",
               "job-name":"curl-job08f8a5bf-3cf4-47b5-b5de-685f8cfe0d01"
            }
         },
         "spec":{
            "containers":[
               {
                  "name":"curl-08f8a5bf-3cf4-47b5-b5de-685f8cfe0d01",
                  "image":"tutum/curl",
                  "command":[
                     "sleep",
                     "5"
                  ],
                  "resources":{

                  },
                  "terminationMessagePath":"/dev/termination-log",
                  "terminationMessagePolicy":"File",
                  "imagePullPolicy":"Always"
               }
            ],
            "restartPolicy":"Never",
            "terminationGracePeriodSeconds":30,
            "dnsPolicy":"ClusterFirst",
            "securityContext":{

            },
            "schedulerName":"default-scheduler"
         }
      }
   },
   "status":{
      "conditions":[
         {
            "type":"Complete",
            "status":"True",
            "lastProbeTime":"2020-03-10T12:06:40Z",
            "lastTransitionTime":"2020-03-10T12:06:40Z"
         }
      ],
      "startTime":"2020-03-10T12:06:31Z",
      "completionTime":"2020-03-10T12:06:40Z",
      "succeeded":1
   }
}
```

**Comment by brendandburns** [comment] 2020-03-10 22:15
This is a duplicate of #86 basically delete methods in Kubernetes can return one of two different objects. There isn't a really great way to handle this in a language like Java that can only have a single return type

The only work around is to catch the exception.

Closing, if you have further input please add it to #86

**Closed by brendandburns** 2020-03-10 22:15 UTC
