### ISSUE TITLE
Kubernetes API throwing ApiException without any error message

### ISSUE THREAD

**Issue by EricBuist** [kubernetes-client/java#2520] opened 2023-01-12 22:25 UTC
**Describe the bug**
Sometimes when I use the Java Kubernetes API, I'm getting repeatedly ApiException without any error message showing what goes wrong exactly. There is no obvious way I can troubleshoot such exceptions, and it will be hard for the API developers to figure anything out as well.
Last time this happened, before the holidays, I could not go on and find a solution. When back from the holidays on January, it started to work again. Then the problem just came back. I have no single clue of what can be wrong if I have no error message of any kind.

The stack trace is the following

``
 io.kubernetes.client.openapi.ApiException:
        at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:974)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:886)
        at io.kubernetes.client.openapi.apis.AppsV1Api.listNamespacedDeploymentWithHttpInfo(AppsV1Api.java:8785)
        at io.kubernetes.client.openapi.apis.AppsV1Api.listNamespacedDeployment(AppsV1Api.java:8673)
...
``

**Client Version**
13.0.2

**Kubernetes Version**
1.24.6

**Java Version**
17.0.5

**To Reproduce**
I got the error from         V1DeploymentList deployments = appsV1Api.listNamespacedDeployment(namespace,
            null, null, null,
            "metadata.name=" + deploymentName, null, null,
            null, null, null, null);

**Expected behavior**
This API call should work and return deployments, or at least an empty list if no deployment matches or the namespace cannot be found.
In case of an API error, the ApiException should have an error message.

**KubeConfig**
This happened on an internal Kubernetes cluster at my workplace, so cannot give a kubeconfig.

**Server (please complete the following information):**
 - OS: Ubuntu 22.04
 - Environment Error first happened locally but also happens on the Kubernetes cluster as well, from a container.
 - Cloud Azure AKS cluster

**Additional context**

**Comment by brendandburns** [comment] 2023-01-12 22:47
I believe this is a duplicate of https://github.com/kubernetes-client/java/issues/2066 which has been fixed in the upstream code generator. We need to pick up the change by re-generating the client.

**Comment by brendandburns** [comment] 2023-01-12 22:48
Closing as a duplicate, please use `/reopen` if this is a mistake.

**Closed by brendandburns** 2023-01-12 22:48 UTC
