### ISSUE TITLE
restartPolicy with Java Client 14.0.0 - Never value is not supported.

### ISSUE THREAD

**Issue by mayankkthr** [kubernetes-client/java#1993] opened 2021-11-17 10:42 UTC
**Describe the bug**
I am unable to use value "Never" for restartPolicy in PodSpec.
My code is as below:

V1PodSpec containerSpec = new V1PodSpec().containers(Arrays.asList(v1Container)).restartPolicy("Never");

As per documentation, the allowed values are - Always, OnFailure, and Never.

**Client Version**
13.0.0, 14.0.0

**Kubernetes Version**
1.21.2

**Java Version**
Java 8

**To Reproduce**

While creating deployment object in your object, make sure you add the restart policy as below:

V1PodSpec containerSpec = new V1PodSpec().containers(Arrays.asList(v1Container))**.restartPolicy("Never")**;

**Expected behavior**
Restart Policy should be set to Never and deployment should be done.

**Server (please complete the following information):**
 - OS: Linux
 - Environment: Pod
 - Cloud: Azure

**Error Message:**
Error: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Deployment.apps \"q8kusa1\" is invalid: spec.template.spec.restartPolicy: Unsupported value: \"Never\": supported values: \"Always\"","reason":"Invalid","details":{"name":"q8kusa1","group":"apps","kind":"Deployment","causes":[{"reason":"FieldValueNotSupported","message":"Unsupported value: \"Never\": supported values: \"Always\"","field":"spec.template.spec.restartPolicy"}]},"code":422}

**Comment by yue9944882** [comment] 2021-11-17 15:24
@mayankkthr this is a server-side rejection which is actually irrelevant w/ the sdk library.. and i suppose u should try the job api if u want the pod to run only once?

**Comment by brendandburns** [comment] 2021-11-17 17:17
Please see the discussion here:
https://github.com/kubernetes/kubernetes/issues/24725

Only `Always` is supported for Deployments.

Closing this issue since it is server side and also working as intended.

**Closed by brendandburns** 2021-11-17 17:17 UTC

**Comment by mayankkthr** [comment] 2021-11-17 18:42
@yue9944882 @brendandburns Thank you for your response.
