### ISSUE TITLE
deleteNamespace() failed

### ISSUE THREAD

**Issue by xianglujun** [kubernetes-client/java#813] opened 2019-11-26 10:28 UTC
i alway fail when i invoke "deleteNamespace()" method.  find reason is that attribute "status" returned as object but V1Status requires string type.

**Comment by brendandburns** [comment] 2019-11-27 05:21
This is a duplicate of #86 please see the discussion there.

Closing this issue since it's a duplicate.

**Closed by brendandburns** 2019-11-27 05:21 UTC

**Comment by xianglujun** [comment] 2019-12-02 09:22
thanks!
