### ISSUE TITLE
Sources jar on maven central incomplete

### ISSUE THREAD

**Issue by kdvolder** [kubernetes-client/java#637] opened 2019-07-26 20:27 UTC
When working with an api in your IDE it is very convenient to be able to browse the source code of the dependenciy/jar.

It seems the source-jar for the client exist but it only has source code for some of the classes. 

Just to take a random example. When I open up io.kubernetes.client.Configuration my IDE (Eclipse in this case, but it shouldn't matter) isn't able to show the source code.

When I look inside the sources jar (the jar can be found on maven central here: https://repo1.maven.org/maven2/io/kubernetes/client-java/5.0.0/ )

I find that there indeed isn't source code  for that class present.

It would nice if you could publish the complete source code on maven central rather than just source code for some of the classes.

**Comment by brendandburns** [comment] 2019-07-26 23:23
There must be some issue with our pom.xml, I admit I'm not familiar enough with Maven to know, but PRs would be welcome (Or eventually someone will dig into this)

**Comment by yue9944882** [comment] 2019-07-29 05:30
it sounds like a duplicate of #596, caused by OSGi bundle packaging.. it should be fixed on master now..

**Comment by kdvolder** [comment] 2019-07-29 16:44
Thanks for the quick response.

> appreciated if you can verify that

Sure, is there a snapshot repo that I can add to my pom.xml to try it? Or do I have to try and build this from source to verify? (Snapshot repo would be easier for me of course :-)

**Closed** 2019-12-26 18:11 UTC
Labels: lifecycle/rotten
