### ISSUE TITLE
okhttpclient connect timeout 

### ISSUE THREAD

**Issue by Deepak-Pandey** [kubernetes-client/java#918] opened 2020-04-17 09:02 UTC
when I was using client-java 4.0.0 following code ensured that connection dosen't timeouts

client = Config.defaultClient();
client.getHttpClient().setReadTimeout(0, TimeUnit.SECONDS);
Configuration.setDefaultApiClient(client);

But I switched to client-java 7.0.0 and using following code 

OkHttpClient httpclient = Config.defaultClient().getHttpClient().newBuilder().readTimeout(0, TimeUnit.seconds).build();
client = Config.defaultClient().setHttpClient(httpclient);
Configuration.setDefaultApiClient(client); 

it is giving connection timeout in about 10s.

**Comment by rjeberhard** [comment] 2020-04-17 11:21
I've not tried setting the timeout on the default client, but instead setting the timeout on the client we are just about to use for a watch:

      OkHttpClient httpClient =
          client.getHttpClient().newBuilder().readTimeout(0, TimeUnit.SECONDS).build();
      client.setHttpClient(httpClient);
      .... watch call

I know this works because we typically have long pauses before watch events on (our case) custom resources.

**Comment by Deepak-Pandey** [comment] 2020-04-17 11:54
has anyone tried for defaultclient??

**Comment by brendandburns** [comment] 2020-04-17 22:12
There are also options for connectTimeout and writeTimeout, is it possible that you are hitting one of those?

**Comment by Deepak-Pandey** [comment] 2020-04-18 12:50
I have tried adding all the three also but it didn't work.

**Comment by Deepak-Pandey** [comment] 2020-04-20 05:29
client = Config.defaultClient();
			
OkHttpClient httpClientclient = new OkHttpClient.Builder()
			        .connectTimeout(0, TimeUnit.SECONDS)
			        .writeTimeout(0, TimeUnit.SECONDS)
			        .readTimeout(0, TimeUnit.SECONDS)
			        .build();
			
client.setHttpClient(httpClientclient);
Configuration.setDefaultApiClient(client);
api = new CoreV1Api();

I am using following code that includes all the three timeouts. Still no luck. getting following exception.

"message":"io.kubernetes.client.openapi.ApiException: javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target"

**Comment by brendandburns** [comment] 2020-04-20 15:55
That exception isn't a timeout. That's some sort of problem with the SSL connection. That error probably means that the certificate authority isn't recognized or loaded correctly. What does your kubeconfig file look like? (anonymize it before sending please)

**Comment by Deepak-Pandey** [comment] 2020-04-21 04:14
can you specify what do you want to see in kubeconfig file. It would be great.

**Comment by brendandburns** [comment] 2020-04-21 04:21
Does `kubectl get nodes` work properly?

I want to see the `certificate-authority` or `certificate-authority-file` sections.

**Comment by Deepak-Pandey** [comment] 2020-04-21 04:23
yes kubectl get nodes works properly.

**Comment by martincyruswolfenbarger** [comment] 2020-04-30 18:39
@Deepak-Pandey in your last example it looks like you switched from using `client.getHttpClient().newBuilder()` to using `new OkHttpClient.Builder()` which is probably what's causing the SSL error.

Also, the code you shared initially worked for me using version 7.0.0. I'm only able to reproduce the timeout if `.readTimeout(0, TimeUnit.SECONDS)` is omitted.

**Comment by brendandburns** [comment] 2020-09-18 18:53
Closing this issue

**Closed by brendandburns** 2020-09-18 18:53 UTC
Labels: lifecycle/rotten
