### ISSUE TITLE
io.kubernetes.client.openapi.ApiException: Forbidden

### ISSUE THREAD

**Issue by xwx606986** [kubernetes-client/java#1459] opened 2020-12-25 02:24 UTC
hello, I have a problem with io.kubernetes.client.openapi.ApiException: Forbidden，When my client use conf like this 
![image](https://user-images.githubusercontent.com/54342359/103114743-dce78380-469a-11eb-9f9c-3f597867d7e3.png), it's normal and correct,  but When I change the way to get the client like this:
![image](https://user-images.githubusercontent.com/54342359/103114811-1cae6b00-469b-11eb-90c2-99f99ecd401e.png)
io.kubernetes.client.openapi.ApiException: Forbidden occurs when I use listNamespacedEndpoints, 
Please help me , thanks

**Comment by xwx606986** [comment] 2020-12-25 02:25
way 1:client = ClientBuilder.kubeconfig(KubeConfig.loadKubeConfig(new FileReader(filePath))).build();-------normal
way 2: client = ClientBuilder.cluster().build();  ------- forbbiden

**Comment by brendandburns** [comment] 2020-12-27 16:52
this is a duplicate of #1439. specifically  the service account associated with your Pod probably doesn't have the right RBAC permissions.

(this is assuming this code is running in a Pod, if it is not running in a Pod, then this code isn't expected to work anyway)

Closing this b/c this is covered in #1439

**Closed by brendandburns** 2020-12-27 16:52 UTC
