### ISSUE TITLE
ExtensionsV1beta1Api.createNamespacedIngress is throwing error for servicePort

### ISSUE THREAD

**Issue by jeesmon** [kubernetes-client/java#117] opened 2017-11-14 17:49 UTC
java-client: v1.0.0-beta1
k8s: v1.8.2

In V1beta1IngressBackend model, servicePort is String. But calling ExtensionsV1beta1Api.createNamespacedIngress with "servicePort": "443" throws 

```
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Ingress.extensions \"ingress\" is invalid: [spec.backend.servicePort: Invalid value: \"443\": must contain at least one letter or number (a-z, 0-9), spec.rules[0].http.backend.servicePort: Invalid value: \"443\": must contain at least one letter or number (a-z, 0-9)]","reason":"Invalid","details":{"name":"ingress","group":"extensions","kind":"Ingress","causes":[{"reason":"FieldValueInvalid","message":"Invalid value: \"443\": must contain at least one letter or number (a-z, 0-9)","field":"spec.backend.servicePort"},{"reason":"FieldValueInvalid","message":"Invalid value: \"443\": must contain at least one letter or number (a-z, 0-9)","field":"spec.rules[0].http.backend.servicePort"}]},"code":422}
```

Serialized version of V1beta1Ingress captured from debug

```
{
    "apiVersion": "extensions/v1beta1",
    "kind": "Ingress",
    "metadata": {
        "annotations": {
            "ingress.kubernetes.io/ssl-passthrough": "true"
        },
        "name": "ingress",
        "namespace": "test"
    },
    "spec": {
        "backend": {
            "serviceName": "svc-1",
            "servicePort": "443"
        },
        "rules": [
            {
                "host": "myhost.com",
                "http": {
                    "paths": [
                        {
                            "backend": {
                                "serviceName": "svc-1",
                                "servicePort": "443"
                            },
                            "path": "/path"
                        }
                    ]
                }
            }
        ],
        "tls": [
            {
                "hosts": [
                    "myhost.com"
                ],
                "secretName": "ingress-secret"
            }
        ]
    }
}
```

```
kubectl apply -f ingress.json 
The Ingress "ingress" is invalid: 
* spec.backend.servicePort: Invalid value: "443": must contain at least one letter or number (a-z, 0-9)
* spec.rules[0].http.backend.servicePort: Invalid value: "443": must contain at least one letter or number (a-z, 0-9)
```

If I change `"servicePort": "443"` to `"servicePort": 443` and run `kubectl apply -f ingress.json`, Ingress is created. But there is no way to do that using the V1beta1Ingress model for java client.

**Comment by brendandburns** [comment] 2017-11-15 01:44
Duplicate of #115 `IntOrString` isn't handled properly.

We need to regenerate the client...

**Comment by brendandburns** [comment] 2017-11-15 06:04
Closing since this is a duplicate.

**Closed by brendandburns** 2017-11-15 06:04 UTC
