### ISSUE TITLE
Extended client not work when at least one api is not available in kubernetes cluster.

### ISSUE THREAD

**Issue by rossignolloic** [kubernetes-client/java#2719] opened 2023-07-03 17:05 UTC
**Describe the bug**
When using extended client to interact with a kubernetes cluster, it will first try to refresh model mapping, for this it will list all available apis in cluster, and then call each of them. When at least one of these apis is unavailable, an exception is thrown and client call is not executed : 
```
io.kubernetes.client.extended.kubectl.exception.KubectlException: io.kubernetes.client.openapi.ApiException:
        at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.refreshDiscovery(Kubectl.java:238)
        at io.kubernetes.client.extended.kubectl.KubectlGet.execute(KubectlGet.java:60)
        ...
Caused by: io.kubernetes.client.openapi.ApiException:
        at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:973)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
        at io.kubernetes.client.Discovery.get(Discovery.java:174)
        at io.kubernetes.client.Discovery.resourceDiscovery(Discovery.java:156)
        at io.kubernetes.client.Discovery.findAll(Discovery.java:71)
        at io.kubernetes.client.Discovery.findAll(Discovery.java:65)
        at io.kubernetes.client.Discovery.findAll(Discovery.java:55)
        at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:260)
        at io.kubernetes.client.util.ModelMapper.refresh(ModelMapper.java:240)
        at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.refreshDiscovery(Kubectl.java:236)
```

**Client Version**
`18.0.0`

**To Reproduce**
Register an api in error in kubernetes cluster: 
```
cat << EOF | kubectl apply -f -
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1alpha1.bug.reproduce.java-client
spec:
  service:
    name: not-existing-service
    namespace: default
  group: bug.reproduce.java-client
  version: v1alpha1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 10
  versionPriority: 10
EOF
```
Use the extended client: `Kubectl.get(V1Deployment.class).execute()`

It will fail because the previously created apiService is not available.

**Expected behavior**
The extended client call should be executed even if another api is unavailable in cluster

**Comment by brendandburns** [comment] 2023-07-07 20:52
I agree this is a bug. We'd be happy to take a PR to fix it, or we'll get to it eventually.

**Comment by relentless-pursuit** [comment] 2023-07-13 18:04
I have been able to reproduce the issue in my local. However, since I am new to Kubernetes, I am a bit apprehensive of whether I would be able to solve it. But, I will try to update in next 24 hours about my progress. And, maybe if i find something substantial, i could be assigned this issue.

**Comment by ramanpopli** [comment] 2023-07-15 15:07
@relentless-pursuit I believe the solution you proposed is worth considering for this issue. However, before implementing it, we should carefully evaluate the implications of continuing execution when an API is unavailable during model mapping refresh. It raises questions about the desired behavior: should we proceed and potentially miss out on necessary APIs, or would it be more appropriate to handle the exception and provide feedback to the user or explore alternative actions? 

@rossignolloic, could you provide your insights on this matter? Your perspective would be valuable in making an informed decision. Thank you!

**Comment by Aman254** [comment] 2023-07-15 19:18
Hey! @brendandburns Can you please guide me, what should I learn to understand issues in kubernetes-java and resolve issues 
as am a beginner and I only know JAVA

**Comment by rossignolloic** [comment] 2023-07-17 08:44
Thanks for the proposal. I have an idea to solve the problem, but I'm currently busy. I will propose a PR this week.
As a preview, i don't think that discovery should be stopped when an api is in error, because discovery fill some metadata in ModelMapper that will not be set in another way.

**Comment by brendandburns** [comment] 2023-07-17 20:28
In general the principle of this client is that we will emulate `kubectl` behavior in a similar situation. Someone should validate, but I'm pretty certain that `kubectl` continues to operate even when there is an api unavailable. Should be easy enough to check with `kubectl get pods` on a cluster in that state.

Thanks again for taking this on!

**Comment by sbmvirdi** [comment] 2023-07-26 08:08
Hi, Im new to kubenetes client but i wanted to contribute to get started, i have previously worked with kubernetes via CLI and has some basic foundation knowledge about it. can someone guide me how to get started with this project and is this issue resolved already. seeking help would appreciate if someone can guide me once i'll get basics right i'll be very happy to be an active contributor.

**Comment by relentless-pursuit** [comment] 2023-07-26 08:24
> Hi, Im new to kubenetes client but i wanted to contribute to get started, i have previously worked with kubernetes via CLI and has some basic foundation knowledge about it. can someone guide me how to get started with this project and is this issue resolved already ? Seeking help, Would appreciate if someone can guide me once i'll get basics right i'll be very happy to be an active contributor.

A PR has already been linked to the issue. Maybe, you can go through the PR and get a better grasp of the issue.

**Closed** 2023-08-08 17:04 UTC
Labels: good first issue
