### ISSUE TITLE
deleteNamespacedJob()  do not delete pod

### ISSUE THREAD

**Issue by qijianan777** [kubernetes-client/java#777] opened 2019-11-06 02:16 UTC
I use deleteNamespacedJob() to delete the job, but it throw a error [issuse86](https://github.com/kubernetes-client/java/issues/86).I catch the error but find the pod is  still exist. How can I delete the job and pod at the same time, use deleteNamespacedJob() and deleteNamespacedPod()?
My client version is 5.0.0

**Comment by brendandburns** [comment] 2019-11-07 19:04
Deleting jobs doesn't delete the pods by design. See the discussion here:

https://stackoverflow.com/questions/41385403/how-do-i-automatically-remove-completed-kubernetes-jobs

Closing this issue as it is answered. Please use `/reopen` if you want to reopen the issue for any reason.

**Closed by brendandburns** 2019-11-07 19:04 UTC
