### ISSUE TITLE
Expected a string but was BEGIN_OBJECT when V1Status deleteResult = api.deleteNamespacedResourceQuota(....) 

### ISSUE THREAD

**Issue by cwchoe** [kubernetes-client/java#1364] opened 2020-11-06 05:58 UTC
The error message is..

[ERROR] [42] 2020-11-06 14:52:59.347 |http-nio-8080-exec-2|ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]|[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 425 path $.status] with root cause
java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 425 path $.status
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:?]
	at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:138) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.ApiClient.deserialize(ApiClient.java:757) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:958) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.apis.CoreV1Api.deleteNamespacedResourceQuotaWithHttpInfo(CoreV1Api.java:22897) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.apis.CoreV1Api.deleteNamespacedResourceQuota(CoreV1Api.java:22827) ~[client-java-api-9.0.2.jar:?]
	at com.skhynix.aip.foundation.wfmanager.taskmgr.runner.Quota.deleteObject(Quota.java:241) ~[classes/:?]
	at com.skhynix.aip.foundation.wfmanager.taskmgr.service.GeneralServiceImpl.deleteQuota(GeneralServiceImpl.java:76) ~[classes/:?]

**Comment by cwchoe** [comment] 2020-11-06 06:21
Java Client Version is 9.0.2

**Comment by brendandburns** [comment] 2020-11-06 15:26
This is a duplicate of #86 please see the detail in that issue. tl; dr; Delete can return multiple types, Swagger can only handle one.

You have two choices, you can catch the exception and handle it, or you can use the GenericAPI to delete objects. There's more details in the issue.

**Closed by brendandburns** 2020-11-06 15:26 UTC
