### ISSUE TITLE
Cloud not dump Service target port properly

### ISSUE THREAD

**Issue by kaizhaokover** [kubernetes-client/java#376] opened 2018-09-28 06:49 UTC
``V1Service service = new V1Service();
        service.apiVersion("v1");
        service.kind("Service");
        V1ObjectMeta sMeta = new V1ObjectMeta();
        sMeta.name(APP_PREFIX+"-expose-svc-" + app.getId());
        sMeta.namespace(namespaceName);
        Map<String, String> svcLabels = new HashMap<>();
        svcLabels.put("svc", APP_PREFIX+"-expose-svc");
        sMeta.labels(svcLabels);
        service.metadata(sMeta);

        V1ServiceSpec spec = new V1ServiceSpec();
        spec.sessionAffinity("ClientIP");
        spec.type("NodePort");
        spec.selector(podLabels);
        List<V1ServicePort> spList = new ArrayList<>();
        V1ServicePort sp = new V1ServicePort();
        sp.protocol("TCP");
        sp.port(INNER_PORT);
        sp.name("client");
        sp.targetPort(new IntOrString(INNER_PORT));
        sp.nodePort(exposeServiceVo.getMappingPort());
        spList.add(sp);

        spec.ports(spList);

        service.spec(spec);

when i use api:Yaml.getSnakeYaml().dumpAll() to dump this object 
the yaml file shows target port as a empty object ->  targetPort: {}

![image](https://user-images.githubusercontent.com/13924923/46192417-92e18d00-c32d-11e8-869e-223289365648.png)

Am i using this API wrong ? Is there any solution for this scenario?

**Comment by brendandburns** [comment] 2018-10-02 00:53
Hrm, my guess is that SnakeYAML doesn't understand the special `IntOrString` class that we have.

We'll need to register it, I'll look into doing that.

Thanks for the report!

**Comment by brendandburns** [comment] 2018-10-02 03:30
Hrm,
I can't seem to reproduce this... Here's what I tried:

```java
    V1Service svc =
    new V1ServiceBuilder()
        .withNewMetadata()
            .withName("aservice")
        .endMetadata()
        .withNewSpec()
            .withSessionAffinity("ClientIP")
            .withType("NodePort")
            .addNewPort()
                .withProtocol("TCP")
                .withName("client")
                .withPort(8008)
                .withNodePort(8080)
                .withTargetPort(new IntOrString(8080))
            .endPort()
        .endSpec()
    .build();
    System.out.println(Yaml.dump(svc));
```

But it prints out as expected. Can you send a complete repro?

Thanks

**Comment by brendandburns** [comment] 2018-10-10 03:14
Closing as could not reproduce, please re-open with a complete repro if you want further exploration.

Thanks!

**Closed by brendandburns** 2018-10-10 03:14 UTC

**Comment by kaizhaokover** [comment] 2018-10-22 07:28
@brendandburns  so sorry for not replying your comment. 

where does this class V1ServiceBuilder  come from ? i can't find this class.
I am using "new new V1ServiceSpec();" api ,is there any difference between them?

**Comment by kaizhaokover** [comment] 2018-10-22 07:38
why can't i  re-open this issue

**Comment by kaizhaokover** [comment] 2018-10-22 08:16
recreate another issue https://github.com/kubernetes-client/java/issues/397#issue-372428974
