### ISSUE TITLE
copy.copyFileFromPod() always throws java.io.IOException: Pipe broken

### ISSUE THREAD

**Issue by bhardwahnitish19** [kubernetes-client/java#908] opened 2020-04-05 06:52 UTC
Hi,

I am using 'io.kubernetes.client-java:8.0.0' with java 11.0.6 and k8s v1.15. I am facing a weird issue in copying some files from pod. I am using minikube on ubuntu and container has a base image of linux OS as well.

     try{
        InputStream dataStream = copy.copyFileFromPod("default", "myPod", "/etc/server/tls-cert.pem");
        final byte[] bytes = IOUtils.toByteArray(dataStream);
        String content = new String(bytes, StandardCharsets.UTF_8);
         log.info("TLS cert of CA:: {}", content);
       } catch (Exception e){
                   log.error("could not read tlsFile", e);
          }

Despite of the file being present at that location, this always throws: 

    java.io.IOException: Pipe broken
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:321) ~[na:na]
	at java.base/java.io.PipedInputStream.read(PipedInputStream.java:377) ~[na:na]
	at java.base/java.io.InputStream.read(InputStream.java:205) ~[na:na]
	at org.apache.commons.codec.binary.BaseNCodecInputStream.read(BaseNCodecInputStream.java:159) ~[commons-codec-1.13.jar:1.13]
	at java.base/java.io.FilterInputStream.read(FilterInputStream.java:107) ~[na:na]
	at org.apache.commons.compress.utils.IOUtils.copy(IOUtils.java:85) ~[commons-compress-1.19.jar:1.19]
	at org.apache.commons.compress.utils.IOUtils.copy(IOUtils.java:60) ~[commons-compress-1.19.jar:1.19]
	at org.apache.commons.compress.utils.IOUtils.toByteArray(IOUtils.java:226) ~[commons-compress-1.19.jar:1.19]
	at com.hlf.admin.console.apiserver.controller.FabricCAController.addKubeConfig(FabricCAController.java:71) ~[main/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:106) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883) ~[spring-webmvc-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53) ~[tomcat-embed-websocket-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at com.hlf.admin.console.apiserver.filter.SimpleCORSFilter.doFilter(SimpleCORSFilter.java:27) ~[main/:na]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) ~[spring-web-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:367) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1639) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) ~[tomcat-embed-core-9.0.31.jar:9.0.31]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

Strange thing is _ByteStreams.copy(dataStream, System.out);_  prints the file content on console but it throws the same exception after couple of seconds.

**Comment by brendandburns** [comment] 2020-04-06 04:29
There's probably something in the way things are closing that isn't working right, I will try to reproduce this locally. Are you just running that program on the command line?

**Comment by bhardwahnitish19** [comment] 2020-04-06 08:19
No, I am running it in Intellij as a spring boot app.

**Comment by bhardwahnitish19** [comment] 2020-04-08 03:53
@brendanburns Any luck in reproducing the issue in your local environment?

**Comment by yue9944882** [comment] 2020-04-08 04:05
inside your `copy` instance, there's an ApiClient which has a default read timeout of 10-ish seconds. overriding the timeout will probably solve the case.

https://github.com/kubernetes-client/java/blob/3cce84bcd5698706c474a08dbf15be9abeb23f51/examples/src/main/java/io/kubernetes/client/examples/InformerExample.java#L25-L28

**Comment by bhardwahnitish19** [comment] 2020-04-08 08:25
@yue9944882  Thanks for the suggestion. I just followed Copy sample
```
  Copy copy = new Copy();
    InputStream dataStream = copy.copyFileFromPod(namespace, podName, "/etc/motd");
    ByteStreams.copy(dataStream, System.out);

```

It printed the content on console but then program halt there until it throws pipe broken exception. Though I will try to extend the timeout but I don't think the issue is related to it.

**Comment by bhardwahnitish19** [comment] 2020-04-09 06:04
@yue9944882 It throws the same exception after 20 secs, timeout  value used 100 secs.

**Comment by bhardwahnitish19** [comment] 2020-04-15 14:09
Hi, are you guys able to replicate the issue in local environment?

**Comment by sagarbhavsar4328** [comment] 2020-04-16 07:45
I was able to reproduce the issue. The problem is `dataStream.read()` never returned -1 i.e. the end of the stream. 
copy internally use exec process and I suspect the process is not closed/terminated properly.

**Comment by bhardwahnitish19** [comment] 2020-04-16 10:27
@sagarbhavsar4328  That's good. :) thanks for confirmation. 

Any plans for fixing it? I am stuck bcz of this issue. :(

Would really appreciate if you guys plan to fix it. 

Thanks

**Comment by bhardwahnitish19** [comment] 2020-04-18 07:38
@sagarbhavsar4328 Thanks for your quick response. Please let me know the latest version having a fix for this once it's merged.

**Comment by bhardwahnitish19** [comment] 2020-05-02 01:53
Hi @sagarbhavsar4328 Thanks for merging this. Could you please let me know which version would have this fix? I can't find any other version over maven other than 8.0.0.

Appreciate your help.

**Comment by sagarbhavsar4328** [comment] 2020-05-02 08:17
@brendandburns can answer regarding the next release or availability in the maven repo.

**Comment by brendandburns** [comment] 2020-05-11 20:21
The `8.0.1` release was just pushed out to the maven servers should be available in 1 day or so.

Closing this issue.

**Closed by brendandburns** 2020-05-11 20:21 UTC

**Comment by bhardwahnitish19** [comment] 2020-05-19 04:54
@brendanburns Thanks for merging this. But, I am still not able to find the latest version in Maven https://mvnrepository.com/artifact/io.kubernetes/client-java

I would really appreciate if you can point me towards v8.0.1.
