### ISSUE TITLE
Unable to build the java client library on Windows

### ISSUE THREAD

**Issue by Invictus17** [kubernetes-client/java#1032] opened 2020-07-02 16:34 UTC
Hi, 
I'm trying to install the java client for Kubernetes and getting an error when building the client-java-api:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Kubernetes Client API 9.0.0-SNAPSHOT:
[INFO]
[INFO] Kubernetes Client API .............................. SUCCESS [  0.149 s]
[INFO] client-java-api .................................... FAILURE [02:33 min]
[INFO] client-java-proto .................................. SKIPPED
[INFO] client-java ........................................ SKIPPED
[INFO] client-java-extended ............................... SKIPPED
[INFO] client-java-spring-integration ..................... SKIPPED
[INFO] client-java-examples ............................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  02:34 min
[INFO] Finished at: 2020-07-02T12:25:29-04:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.0.1:jar (attach-javadocs) on project client-java-api: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1 - D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationApi.java:63: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationApi.java:113: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationApi.java:130: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationApi.java:149: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:74: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:147: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:170: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:195: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:220: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:293: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:316: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:341: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:374: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:480: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:509: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:540: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:571: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:677: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:706: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:737: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:763: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:847: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:872: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:899: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:926: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1010: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1035: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1062: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1082: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1132: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1149: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1168: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1196: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1291: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1317: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1345: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1373: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1468: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1494: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1522: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1547: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1630: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1653: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1678: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1703: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1786: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1809: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1834: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1857: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1929: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1950: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1973: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:1996: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2068: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2089: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2112: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2136: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2215: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2238: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2263: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2288: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2367: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2390: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1Api.java:2415: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:74: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:147: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:170: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:195: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:220: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:293: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:316: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:341: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:374: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:480: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:509: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:540: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:571: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:677: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:706: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:737: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:763: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:847: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:872: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:899: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:926: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1010: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1035: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1062: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1082: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1132: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1149: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1168: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1196: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1291: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1317: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1345: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1373: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1468: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1494: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR] D:\Kubernetes open source - Python client\Java example\java\kubernetes\src\main\java\io\kubernetes\client\openapi\apis\AdmissionregistrationV1beta1Api.java:1522: error: attribute not supported in HTML5: summary
[ERROR]      <table summary="Response Details" border="1">
[ERROR]             ^
[ERROR]
[ERROR] Command line was: D:\Softwares\JDK\bin\javadoc.exe @options @packages
[ERROR]
[ERROR] Refer to the generated Javadoc files in 'D:\Kubernetes open source - Python client\Java example\java\kubernetes\target\apidocs' dir.
[ERROR]
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :client-java-api
```
Steps to reproduce:
```
git clone --recursive https://github.com/kubernetes-client/java
cd java
mvn install
```

**Comment by brendandburns** [comment] 2020-07-02 18:08
What version of the JDK are you running? This isn't showing up in our CI/CD or on my machine.

**Comment by Invictus17** [comment] 2020-07-02 19:07
I'm currently running on version 13.0.2.

**Comment by brendandburns** [comment] 2020-07-05 06:00
Can you try downgrading to java 11, that's known to work. I will try to reproduce on java 13.

**Comment by Invictus17** [comment] 2020-07-05 15:57
> Can you try downgrading to java 11, that's known to work. I will try to reproduce on java 13.

I tried it with version 11 & 10, still the same error.

**Comment by Invictus17** [comment] 2020-07-05 21:28
@brendanburns I was able to build it successfully in Linux OS.

**Comment by brendandburns** [comment] 2020-07-06 16:26
That's odd. I will try to reproduce this error on Windows.

**Comment by sarveshkaushal** [comment] 2020-07-07 19:15
I also see this on my MacOS 10.15.5 when I try to build this using Java 11 (openjdk version "11.0.6" 2020-01-14). I was able to fix this by making a change in project pom.xml file. 
```
<plugin>
       <groupId>org.apache.maven.plugins</groupId>
       <artifactId>maven-javadoc-plugin</artifactId>
       <version>3.0.1</version>
       <configuration>
            <doclint>none</doclint>
       </configuration>
  </plugin>
```
After making this change i was able to build the project successfully both on Java 8 and Java 11. The problem is if you are on Java 11, classes under api package has table definition in Java docs. `<table>` tag has _**summary**_ attribute which is deprecated in HTML5.
@brendandburns @yue9944882 - Do you think we can make this change in pom.xml ?

**Comment by brendanburns** [comment] 2020-07-07 20:39
Sure I'd be happy to take a PR with this fix if you want to prepare it.

Thanks!

**Comment by sarveshkaushal** [comment] 2020-07-07 22:51
Will send a PR shortly.

**Comment by brendandburns** [comment] 2020-07-11 04:25
Closing this since #1047 merged.

**Closed by brendandburns** 2020-07-11 04:25 UTC
