### ISSUE TITLE
NullPointer Exception using Kubectl.apply from client-java-extended

### ISSUE THREAD

**Issue by saparaj** [kubernetes-client/java#1561] opened 2021-02-25 02:06 UTC
Hello @brendanburns and @yue9944882,

I am trying to create an ingress using Kubectl.apply as per this: https://github.com/kubernetes-client/java/blob/b0c91798c63203f20dc8f2674197e772b2c187ee/docs/kubectl-equivalence-in-java.md#kubectl-apply
My Kubernetes cluster version: 1.18.10 and java-client version: 10.0.0

Kubectl.apply(NetworkingV1beta1Ingress.class).resource(resource).execute();
I am getting below error:
Exception in thread "main" java.lang.NullPointerException
at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:259)
at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:293)
at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:73)
at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:67)

I tried the same resource with kubectl CLI and I don't see any error:
kubectl apply -f /Users/saparaj/k8s-official-java-client-server-apply/resources/ingress.yml --server-side
ingress.networking.k8s.io/myapp-prod serverside-applied

ingress.yaml

# Ingress service for production
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: myapp-prod
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: myapp
spec:
  rules:
    - host: test.canary.com
      http:
        paths:
          - backend:
              serviceName: myapp-prod
              servicePort: 8088
Please let me know if I am missing something here.

Thanks,
Swarda

**Comment by brendandburns** [comment] 2021-02-25 05:25
The Group/Version/Kind for this object are unknown to the client.

The fact that this returns an NPE is a bug and was fixed in 11.0.0:

https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/kubectl/Kubectl.java#L255

But it will still throw an exception.

The reason for this is that Ingress is an extension API, not packaged as part of the core Kubernetes APIs and thus it isn't being generated for this client.

We should probably consider generating it, since it is a pretty common API, but until then the `Kubectl` family of commands won't work unless you manually register the Group/Version/Kind yourself with the model mapper.

**Comment by yue9944882** [comment] 2021-02-25 06:49
@saparaj did you set the global ApiClient via `Configuration.setDefaultApiClient(..)` or choosing ApiClient explicitly after Kubectl.apply()? e.g.

https://github.com/kubernetes-client/java/blob/6990dc38fc8015e00920306a8f2f31e73e066efc/e2e/src/test/groovy/io/kubernetes/client/e2e/kubectl/KubectlNamespaceTest.groovy#L45

**Comment by saparaj** [comment] 2021-02-25 07:47
I tried both ways..Setting global client like Configuration.setDefaultApiClient(..) as well as explicit api client on method call.
Below file works with the same code. Just updated networking.k8s.io to extensions.
```
# Ingress service for production
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: myapp-prod
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app: myapp
spec:
  rules:
    - host: test.canary.com
      http:
        paths:
          - backend:
              serviceName: myapp-prod
              servicePort: 8088
```

**Comment by yue9944882** [comment] 2021-02-25 08:57
@saparaj i wasn't able to reproduce that by https://github.com/kubernetes-client/java/pull/1562. can you set `ApiClient#setDebugging` to true and share us more logging?

**Comment by saparaj** [comment] 2021-02-25 23:52
I have attached debugging file: 

[debugging.txt](https://github.com/kubernetes-client/java/files/6046366/debugging.txt)

**Comment by brendandburns** [comment] 2021-02-26 05:15
fwiw, I think she using the 10.0.x library, not sure when we started generating Ingress resources.

**Comment by saparaj** [comment] 2021-02-26 06:20
Which is the latest version? I tried 11.0.0 library as well, Not seeing NPE but unknown resource exception.

Exception in thread "main" io.kubernetes.client.extended.kubectl.exception.KubectlException: Unexpected unknown resource type: class io.kubernetes.client.openapi.models.NetworkingV1beta1Ingress
	at io.kubernetes.client.extended.kubectl.Kubectl$ApiClientBuilder.getGenericApi(Kubectl.java:256)
	at io.kubernetes.client.extended.kubectl.Kubectl$ResourceBuilder.getGenericApi(Kubectl.java:297)
	at io.kubernetes.client.extended.kubectl.KubectlApply.executeServerSideApply(KubectlApply.java:73)
	at io.kubernetes.client.extended.kubectl.KubectlApply.execute(KubectlApply.java:67)
	at patchLogic.PatchLogic.apply(PatchLogic.java:89)
	at patchLogic.PatchLogic.main(PatchLogic.java:73)

[debugging11.0.0.txt](https://github.com/kubernetes-client/java/files/6047738/debugging11.0.0.txt)

Thank you for your help.

**Comment by yue9944882** [comment] 2021-02-26 11:15
@saparaj ur apiserver doesn't enable networking.k8s.io/ingress api, using the extension api will be fine.

```
INFO: {"kind":"APIResourceList","apiVersion":"v1","groupVersion":"networking.k8s.io/v1","resources":[{"name":"networkpolicies","singularName":"","namespaced":true,"kind":"NetworkPolicy","verbs":["create","delete","deletecollection","get","list","patch","update","watch"],"shortNames":["netpol"],"storageVersionHash":"YpfwF18m1G8="}]}
```

**Comment by saparaj** [comment] 2021-02-26 19:44
Oh Yes, I tried ```kubectl explain ingress``` and it shows extensions/v1beta1. Thank you so much both of you for your help.

**Closed** 2021-02-26 19:44 UTC
