### ISSUE TITLE
Missing classes when jar version is updated from 8.0.2 to 11.0.0

### ISSUE THREAD

**Issue by srinivasev** [kubernetes-client/java#1584] opened 2021-03-10 14:03 UTC
Hi, I upgraded the client-java version from 8.0.2 to 11.0.0 .

I am unable to see the below classes,

V1beta2Deployment
AppsV1beta1Deployment
ExtensionsV1beta1Deployment
V1beta2DeploymentCondition
AppsV1beta2Api
etc..

What is the reason ?. The client jar should be always backward compatible i feel. 

By referrring the compatibility matrix, https://github.com/kubernetes-client/java/wiki/2.-Versioning-and-Compatibility#compatibility , the classes should have been still there in the latest java client library.

Is it because of this reason - https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/ ?

**Comment by brendandburns** [comment] 2021-03-10 19:46
To set context, this library is generated directly from the Kubernetes API descriptions (OpenAPI Schema) so we follow Kubernetes versions in terms of APIs that are supported.

And yes, that blog explains the things that are removed. The good news is that there are drop-in replacements for all of those objects (e.g. AppsV1Deployment)

Closing this issue since this is working as intended.

**Closed by brendandburns** 2021-03-10 19:46 UTC
