### ISSUE TITLE
Many null parameters in code snippets in examples in README.md

### ISSUE THREAD

**Issue by pwittchen** [kubernetes-client/java#114] opened 2017-11-13 15:16 UTC
Hi,

Don't you think that in code snippets in the examples, methods take too many `null` parameters?

Like here:

```java
V1PodList list = api.listPodForAllNamespaces(null, null, null, null, null, null);
```

or here:

```java
api.listNamespaceCall(null, null, null, null, 5, Boolean.TRUE, null, null)
```

Passing `null` as a parameter is generally bad practice. If we pass many `null`s it's even worse. Can we fix it or update the API in any way to get rid of these `null`s?

Regards,
Piotr

**Comment by brendandburns** [comment] 2017-11-14 06:31
This is a duplicate of https://github.com/kubernetes-client/java/issues/93 closing.

**Closed by brendandburns** 2017-11-14 06:31 UTC
