### ISSUE TITLE
Delete a Pod using Kubernetes Client API

### ISSUE THREAD

**Issue by smaillns** [kubernetes-client/java#657] opened 2019-08-14 16:16 UTC
I want simply to delete a Pod using the code below,
```

        ApiClient client = Config.defaultClient();
//        client.setDebugging(true);
        Configuration.setDefaultApiClient(client);


        CoreV1Api api = new CoreV1Api();


        V1DeleteOptions v1DeleteOptions = new V1DeleteOptions();
        v1DeleteOptions.setApiVersion("v1");
//        v1DeleteOptions.setKind("pod");
        v1DeleteOptions.setOrphanDependents(true);


        V1Status v1Status = api.deleteNamespacedPod(mservice,"default", v1DeleteOptions, null, null, null , null , null);

        return v1Status;
```
But I've some exceptions 

> com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1397 path $.status

I'll appreciate any help

**Comment by yue9944882** [comment] 2019-08-15 10:22
it's a duplicate of #252

**Comment by brendandburns** [comment] 2019-08-16 20:30
Closing as a duplicate.

**Closed by brendandburns** 2019-08-16 20:30 UTC
