### ISSUE TITLE
V1Status not support k8s latest version: 1.18

### ISSUE THREAD

**Issue by github-edu** [kubernetes-client/java#969] opened 2020-06-03 01:37 UTC
JSON filed `status` is Object, not `String`

```json
{
  "kind": "Namespace",
  "apiVersion": "v1",
  "metadata": {
    "name": "created-by-java-1591085118384",
    "selfLink": "/api/v1/namespaces/created-by-java-1591085118384",
    "uid": "5d5cc84d-339d-4e0c-86e5-d287601e928a",
    "resourceVersion": "70213",
    "creationTimestamp": "2020-06-02T08:06:11Z",
    "deletionTimestamp": "2020-06-02T08:07:19Z",
    "managedFields": [
      {
        "manager": "OpenAPI-Generator",
        "operation": "Update",
        "apiVersion": "v1",
        "time": "2020-06-02T08:06:11Z",
        "fieldsType": "FieldsV1",
        "fieldsV1": {"f:status":{"f:phase":{}}}
      }
    ]
  },
  "spec": {
    "finalizers": [
      "kubernetes"
    ]
  },
  "status": {
    "phase": "Terminating"
  }
}
```

**Comment by github-edu** [comment] 2020-06-03 01:39
```java
...

/**
 * Status is a return value for calls that don&#39;t return other objects.
 */
@ApiModel(description = "Status is a return value for calls that don't return other objects.")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2020-04-29T07:27:12.312Z[Etc/UTC]")
public class V1Status {
  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_CODE = "code";
  @SerializedName(SERIALIZED_NAME_CODE)
  private Integer code;

  public static final String SERIALIZED_NAME_DETAILS = "details";
  @SerializedName(SERIALIZED_NAME_DETAILS)
  private V1StatusDetails details;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1ListMeta metadata;

  public static final String SERIALIZED_NAME_REASON = "reason";
  @SerializedName(SERIALIZED_NAME_REASON)
  private String reason;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private String status;
...
```

**Comment by github-edu** [comment] 2020-06-03 01:40
`Cause: JSON deserialization failed`

**Comment by github-edu** [comment] 2020-06-03 01:49
Although the client fails to get the JSON deserialization result of the call, it does not affect the successful execution of the k8s server.

**Comment by yue9944882** [comment] 2020-06-03 03:08
it's a duplicated of https://github.com/kubernetes-client/java/issues/86, consider use https://github.com/kubernetes-client/java/blob/master/extended/src/main/java/io/kubernetes/client/extended/generic/GenericKubernetesApi.java us a workaround

**Comment by brendandburns** [comment] 2020-06-04 23:04
Closing this since it is a duplicate of #86

**Closed by brendandburns** 2020-06-04 23:04 UTC
