### ISSUE TITLE
listNode api error

### ISSUE THREAD

**Issue by chengdonglin** [kubernetes-client/java#3671] opened 2024-08-30 09:56 UTC
I use the next code to test listNode() api:

```
CoreV1Api api = new CoreV1Api(client);
V1NodeList execute = api.listNode().execute();
```
response error: 
Exception in thread "main" java.lang.IllegalArgumentException: Expected the field `names` to be an array in the JSON string but got `null`

I debug find the function`  JSON.deserialize(respBody, returnType)`  thnow the error, 

Client Version 20.0.0
Kubernetes = 1.28.10
java = 17

**Comment by brendandburns** [comment] 2024-08-30 17:45
This is a duplicate of https://github.com/kubernetes-client/java/issues/3076

tl;dr; there is a difference between the swagger schema and the Go JSON library in terms of how it treats empty arrays.

**Comment by brendandburns** [comment] 2024-08-30 17:46
For now you can use the `legacy` version to work around this. We can consider if we want to fix this in the upstream code generator, but honestly, I think this is a bug in the Kubernetes API server.

**Closed** 2024-09-03 01:44 UTC
