### ISSUE TITLE
When can use kubernetes-client/java implement the command of kubectl drain，I saw that the code was merged

### ISSUE THREAD

**Issue by ssvvnn** [kubernetes-client/java#1357] opened 2020-11-02 06:19 UTC

**Comment by yue9944882** [comment] 2020-11-02 06:23
@ssvvnn this is already released at version 10.0.0

**Comment by ssvvnn** [comment] 2020-11-02 06:47
is it in the package named entended ?  but I can not find it， and my version is 10.0.0

**Comment by ssvvnn** [comment] 2020-11-02 06:48
> @ssvvnn this is already released at version 10.0.0

is it in the package named entended ? but I can not find it， and my version is 10.0.0

**Comment by yue9944882** [comment] 2020-11-02 07:36
it's `io.kubernetes.client.extended.kubectl.Kubectl.drain(..)`. am sure it's published in 10.0.0.

**Comment by ssvvnn** [comment] 2020-11-02 08:18
> it's `io.kubernetes.client.extended.kubectl.Kubectl.drain(..)`. am sure it's published

**Comment by ssvvnn** [comment] 2020-11-02 08:23
> > it's `io.kubernetes.client.extended.kubectl.Kubectl.drain(..)`. am sure it's published

Sorry， I indeed can find it，io.kubernetes.client.extended has not exits at version 10.0.0，was you sure published in maven repository?

**Comment by yue9944882** [comment] 2020-11-02 09:36
yes, the badge on the README page will show you the latest version in the central repo

**Comment by brendandburns** [comment] 2020-11-03 00:12
In particular:
https://search.maven.org/search?q=a:client-java-extended

**Comment by brendandburns** [comment] 2020-11-03 00:14
I downloaded and examined that jar:

```sh
jar -tf Downloads/client-java-extended-10.0.0.jar | grep Kubectl
io/kubernetes/client/extended/kubectl/Kubectl$ApiClientBuilder.class
io/kubernetes/client/extended/kubectl/Kubectl$Executable.class
io/kubernetes/client/extended/kubectl/Kubectl$NamespacedApiClientBuilder.class
io/kubernetes/client/extended/kubectl/Kubectl$ResourceAndContainerBuilder.class
io/kubernetes/client/extended/kubectl/Kubectl$ResourceBuilder.class
io/kubernetes/client/extended/kubectl/Kubectl.class
io/kubernetes/client/extended/kubectl/KubectlAnnotate.class
io/kubernetes/client/extended/kubectl/KubectlApiResources.class
io/kubernetes/client/extended/kubectl/KubectlApply.class
io/kubernetes/client/extended/kubectl/KubectlCopy.class
io/kubernetes/client/extended/kubectl/KubectlCordon.class
io/kubernetes/client/extended/kubectl/KubectlCreate.class
io/kubernetes/client/extended/kubectl/KubectlDelete.class
io/kubernetes/client/extended/kubectl/KubectlDrain.class
io/kubernetes/client/extended/kubectl/KubectlExec$1.class
io/kubernetes/client/extended/kubectl/KubectlExec.class
io/kubernetes/client/extended/kubectl/KubectlGet$1.class
io/kubernetes/client/extended/kubectl/KubectlGet$KubectlGetSingle.class
io/kubernetes/client/extended/kubectl/KubectlGet.class
io/kubernetes/client/extended/kubectl/KubectlLabel.class
io/kubernetes/client/extended/kubectl/KubectlLog.class
io/kubernetes/client/extended/kubectl/KubectlPatch.class
io/kubernetes/client/extended/kubectl/KubectlPortForward$1.class
io/kubernetes/client/extended/kubectl/KubectlPortForward.class
io/kubernetes/client/extended/kubectl/KubectlReplace.class
io/kubernetes/client/extended/kubectl/KubectlScale.class
io/kubernetes/client/extended/kubectl/KubectlTaint.class
io/kubernetes/client/extended/kubectl/KubectlTop$1.class
io/kubernetes/client/extended/kubectl/KubectlTop$2.class
io/kubernetes/client/extended/kubectl/KubectlTop.class
io/kubernetes/client/extended/kubectl/KubectlVersion.class
io/kubernetes/client/extended/kubectl/exception/KubectlException.class
```

Closing this issue because I think the issue is resolved. Please use `/reopen` if you need more assistance.

**Closed** 2020-11-03 00:14 UTC

**Comment by ssvvnn** [comment] 2020-11-03 07:40
> In particular:
> https://search.maven.org/search?q=a:client-java-extended

Thanks
