### ISSUE TITLE
Exec process does not terminate when the command execution is completed

### ISSUE THREAD

**Issue by Zanis7** [kubernetes-client/java#928] opened 2020-04-22 07:57 UTC
I'm just trying to list the files in a pod and send it as response in my web application.

Sample code to reproduce the issue:

`import com.google.common.io.ByteStreams;

import io.kubernetes.client.Exec;
import io.kubernetes.client.openapi.ApiClient;
import io.kubernetes.client.openapi.Configuration;
import io.kubernetes.client.util.Config;

public class ExecTest {
	public static void main(String[] args) throws Exception {
		ApiClient client = Config.fromConfig("/home/local/.kube/config");
        Configuration.setDefaultApiClient(client);
		Exec exec = new Exec();
		Process proc= exec.exec("default", "tomcattest-64c97b9fd8-9hz95", new String[]{"ls"}, false);
		ByteStreams.copy(proc.getInputStream(), System.out);
	}
}`

The response of the "ls" command is printed in standard output. But the thread stuck at ByteStreams.copy line,after some time I'm getting "java.io.IOException: Pipe broken" Exception and the program exits.

Why the ByteStreams.copy waiting for inputstream read even though the command execution is completed? Am I missing something ?

**Comment by bhardwahnitish19** [comment] 2020-04-22 08:09
I guess this issue is a duplicate of issue [908](https://github.com/kubernetes-client/java/issues/908)

FYI - @brendandburns, @sagarbhavsar4328

**Comment by zxyxz** [comment] 2020-08-21 05:36
I had the same problem

**Comment by zxyxz** [comment] 2020-08-21 05:36
version 8.0.2

**Comment by brendandburns** [comment] 2020-09-18 18:54
This is expected, especially if the server terminates the connection. You need to catch and handle this exception.

**Closed by brendandburns** 2020-09-18 18:54 UTC
Labels: lifecycle/rotten
