### ISSUE TITLE
Pod Informer shutting down abruptly

### ISSUE THREAD

**Issue by sunilkrg** [kubernetes-client/java#1160] opened 2020-08-16 03:42 UTC
Kubernetes-client-java - 6.0.1

Kubernetes server version - 1.16.8
Kubernetes client version - 1.17

We start the pod Informer as soon as our Spring boot application starts. Everything was working fine until we increased the resources and limit of the deployment of our application to handle the increasing load and a property of tomcat, server.tomcat.max-threads to 800. The replica is 1.

Earlier,
The pod Informer used to start with the application and kept on running, and watching pods in different namespaces

Now
The pod Informer starts with the application start but stops anytime to track the pods. I did not find any logs associated with its failure.

Please help here if these configuration changes can hamper in any way

**Comment by yue9944882** [comment] 2020-08-18 11:19
i can't see the cause of your issue from description. but can you try upgrade the version to `9.0.0`? there were couple of bugfixes after `6.0.1`

**Comment by brendandburns** [comment] 2020-09-18 18:41
Closing this issue as obsolete due to using `6.0.1`

**Closed by brendandburns** 2020-09-18 18:41 UTC
