### ISSUE TITLE
resourceVersion has not change，but  Informer onUpdate function executed

### ISSUE THREAD

**Issue by zzl-code** [kubernetes-client/java#1234] opened 2020-09-07 08:28 UTC
I have write a informer to watch deployment，but deployment has not change，resourceVersion has not change，but  Informer onUpdate function executed。
          ` ApiClient apiClient=kubeClientManager.formatJavaSDKClient(cluster.getK8sId());

                ExtensionsV1beta1Api appsV1Api=new ExtensionsV1beta1Api(apiClient);

                SharedInformerFactory factory = new SharedInformerFactory();
                SharedIndexInformer<ExtensionsV1beta1Deployment> deploymentInformer=factory.sharedIndexInformerFor((CallGeneratorParams callGeneratorParams) -> {
                    try {

                        log.info(callGeneratorParams.toString());
                        return appsV1Api.listNamespacedDeploymentCall(
                                cluster.getNamespace(),
                                null,
                                null,
                                null,
                                null,
                                null,
                                null,
                                callGeneratorParams.resourceVersion,
                                callGeneratorParams.timeoutSeconds,
                                callGeneratorParams.watch,
                                null);
                    } catch (ApiException e) {
                        e.printStackTrace();
                        return null;
                    }
                }, ExtensionsV1beta1Deployment.class, ExtensionsV1beta1DeploymentList.class);

                deploymentInformer.addEventHandler(
                        new ResourceEventHandler<ExtensionsV1beta1Deployment>() {
                            @Override
                            public void onAdd(ExtensionsV1beta1Deployment v1Deployment) {
                                log.info("add"+v1Deployment.getMetadata().getName());
                                if(v1Deployment.getMetadata().getName().equals("project-normal-dev")){
                                    log.info(v1Deployment.toString());
                                }
                            }

                            @Override
                            public void onUpdate(ExtensionsV1beta1Deployment v1Deployment, ExtensionsV1beta1Deployment apiType1) {
                                log.info("update"+v1Deployment.getMetadata().getName());

                                if(v1Deployment.getMetadata().getName().equals("project-normal-dev")){
                                    log.info(v1Deployment.toString());
                                }
                            }

                            @Override
                            public void onDelete(ExtensionsV1beta1Deployment v1Deployment, boolean b) {
                                log.info("delete"+v1Deployment.getMetadata().getName());
                            }
                        });
                factory.startAllRegisteredInformers();`

**Comment by yue9944882** [comment] 2020-09-08 08:22
@zzl-code i think that's the expected behavior and aligns w/ the golang library, underneath the informer there's a daemon thread doing list-watch periodically and everytime it re-lists the objects, it sends UPDATE notification to the handlers

**Comment by brendandburns** [comment] 2020-09-18 18:33
Closing this issue since the question is answered. Please open a new issue if you need further assistance.

**Closed by brendandburns** 2020-09-18 18:33 UTC
