### ISSUE TITLE
Expected a string but was BEGIN_OBJECT at line 1 column 1421 path $.status

### ISSUE THREAD

**Issue by PascalKu** [kubernetes-client/java#456] opened 2018-12-05 20:49 UTC
> java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1421 path $.status
> 	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:825) ~[gson-2.8.2.jar:na]
> 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:401) ~[gson-2.8.2.jar:na]
> 	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:389) ~[gson-2.8.2.jar:na]
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129) ~[gson-2.8.2.jar:na]
> 	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220) ~[gson-2.8.2.jar:na]
> 	at com.google.gson.Gson.fromJson(Gson.java:888) ~[gson-2.8.2.jar:na]
> 	at com.google.gson.Gson.fromJson(Gson.java:853) ~[gson-2.8.2.jar:na]
> 	at com.google.gson.Gson.fromJson(Gson.java:802) ~[gson-2.8.2.jar:na]
> 	at io.kubernetes.client.JSON.deserialize(JSON.java:108) ~[client-java-3.0.0.jar:na]
> 	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668) ~[client-java-3.0.0.jar:na]
> 	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871) ~[client-java-3.0.0.jar:na]
> 	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798) ~[client-java-3.0.0.jar:na]
> 	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPodWithHttpInfo(CoreV1Api.java:13152) ~[client-java-api-3.0.0.jar:na]
> 	at io.kubernetes.client.apis.CoreV1Api.deleteNamespacedPod(CoreV1Api.java:13132) ~[client-java-api-3.0.0.jar:na]

Deleting pod using:

```
final V1DeleteOptionsBuilder builder = new V1DeleteOptionsBuilder()
                    .withNewPreconditions()
                    .and();

kubernetesClient.getApiClient().deleteNamespacedPod( "podId", "development", builder.build(), null, 5, null, null )
```

Gson-Version: 

> <dependency>
>             <groupId>com.google.code.gson</groupId>
>             <artifactId>gson</artifactId>
>             <version>2.8.2</version>
>             <scope>compile</scope>
>         </dependency>

**Comment by PascalKu** [comment] 2018-12-05 20:50
Also not working with the newest version 2.8.5

**Comment by brendandburns** [comment] 2018-12-06 05:51
Duplicate of #86, please see the details in that issue about why this happens (and why we can't fix it right now)

**Closed by brendandburns** 2018-12-06 05:51 UTC
