### ISSUE TITLE
Bug when deleteNamespacedCronJob

### ISSUE THREAD

**Issue by zhengyangyong** [kubernetes-client/java#1133] opened 2020-08-03 13:10 UTC
kubernetes version : 1.16.4
java client version : 8.0.2

```java
    BatchV1beta1Api batchV1beta1Api = new BatchV1beta1Api();
    V1Status status = batchV1beta1Api.deleteNamespacedCronJob(name, namespace, "true", null, null, null, null, null);
```

Exception Trace:
```text
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 69 column 14 path $.status
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
	at com.google.gson.Gson.fromJson(Gson.java:932)
	at com.google.gson.Gson.fromJson(Gson.java:897)
	at com.google.gson.Gson.fromJson(Gson.java:846)
	at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:139)
	at io.kubernetes.client.openapi.ApiClient.deserialize(ApiClient.java:765)
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:968)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
	at io.kubernetes.client.openapi.apis.BatchV1beta1Api.deleteNamespacedCronJobWithHttpInfo(BatchV1beta1Api.java:582)
	at io.kubernetes.client.openapi.apis.BatchV1beta1Api.deleteNamespacedCronJob(BatchV1beta1Api.java:554)
```

**Comment by brendandburns** [comment] 2020-08-03 22:09
This is a duplicate of #86, there's much more detail in that issue, but basically Kubernetes can return two different types here and we only parse one of them correctly. There's not much we can do for now to fix it.

**Closed by brendandburns** 2020-08-03 22:09 UTC

**Comment by zhengyangyong** [comment] 2020-08-04 01:57
Thanks~
