### ISSUE TITLE
k8s client api : Unable to fetch pod list when validateSSL is true

### ISSUE THREAD

**Issue by miniraj87** [kubernetes-client/java#299] opened 2018-06-27 10:30 UTC
ApiClient client = Config.fromToken(connectionurl, apitoken, validateSSL);
Configuration.setDefaultApiClient(client);

When connection url is https://... and validateSSL is true, i get below exception
xception in thread "main" io.kubernetes.client.ApiException: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:801)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPodWithHttpInfo(CoreV1Api.java:16691)
	at io.kubernetes.client.apis.CoreV1Api.listNamespacedPod(CoreV1Api.java:16668)

Is there any wayout to run secured url with validateSSL true?
when validateSSL = false, it works fine.

**Comment by brendandburns** [comment] 2018-06-28 23:30
In general, this should work (and I have examples on my machine where it does work) 

So, my guess is that the CA certificate is missing from your kubeconfig file, but without knowing the details of what your config file it's hard to say specifically what is missing.

Does the kubeconfig file work when used with `kubectl`?

Thanks
--brendan

**Comment by miniraj87** [comment] 2018-06-29 01:55
I am using Config.fromToken() api so it does not kubeconfig file. I just need to use this api its third parameter is true that is validateSSL.
And yes kubeconfig file worked.

**Comment by brendandburns** [comment] 2018-06-29 20:22
In order to do that you will need to also add the CA certificate in from the kubeconfig file.

You may have to explicitly use a builder to do this. See: https://github.com/kubernetes-client/java/blob/master/util/src/main/java/io/kubernetes/client/util/Config.java#L67

Closing this issue, since this is working as intended, I think.  Please re-open if further info.

**Closed by brendandburns** 2018-06-29 20:22 UTC
