### ISSUE TITLE
mvn install/package  -DskipTests is error

### ISSUE THREAD

**Issue by GWCLBN** [kubernetes-client/java#914] opened 2020-04-09 12:47 UTC
I try jdk8 and jdk11 on win10， thhe following errors have occurred

[ERROR] /F:/study-k8s-operator/java-client-java-parent-6.0.1/kubernetes/target/generated-sources/annotations/io/kubernetes/client/fluent/BaseFluent.java:[36,49] 不兼容的类型: java.lang.Object无法转换为io.kubernetes.client.fluent.Builder<? extends T>
[ERROR] /F:/study-k8s-operator/java-client-java-parent-6.0.1/kubernetes/target/generated-sources/annotations/io/kubernetes/client/fluent/BaseFluent.java:[47,49] 不兼容的类型: java.lang.Object无法转换为io.kubernetes.client.fluent.Builder<? extends T>
[INFO] 2 errors
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Kubernetes Client API .............................. SUCCESS [  0.110 s]
[INFO] client-java-api .................................... FAILURE [ 39.982 s]

**Comment by brendandburns** [comment] 2020-04-09 23:29
I think this is a duplicate of #795 there's more details in that issue, can you check to see if it matches?

**Comment by GWCLBN** [comment] 2020-04-10 04:33
> I think this is a duplicate of #795 there's more details in that issue, can you check to see if it matches?

jdk8 It's work

yesterday, I installed jdk8 ( jdk-8u241-windows-x64.exe) and no env （JAVA_HOME）configured, but my JAVA_HOME is jdk13 installed with jdk-13.0.1_windows-x64_bin.zip. 

mvn used JAVA_HOME  not the system java.

This may be a java version issue.  jdk11  jdk13  jdk14 is the same error!

**Comment by GWCLBN** [comment] 2020-04-10 04:35
> > I think this is a duplicate of #795 there's more details in that issue, can you check to see if it matches?
> 
> jdk8 It's work
> 
> yesterday, I installed jdk8 ( jdk-8u241-windows-x64.exe) and no env （JAVA_HOME）configured, but my JAVA_HOME is jdk13 installed with jdk-13.0.1_windows-x64_bin.zip.
> 
> mvn used JAVA_HOME not the system java.
> 
> This may be a java version issue. jdk11 jdk13 jdk14 is the same error!

 Thank you so much

**Comment by brendandburns** [comment] 2020-04-13 16:14
Yeah, there's a problem with the fluent generator on later JVMs, not sure what the issue is. We may need to disable it.

This is confirmed to be a duplicate of #795 so I'm going to close this issue in favor of that one.

If you need to reopen for any reason, please use the `/reopen` command.

**Closed by brendandburns** 2020-04-13 16:14 UTC
