### ISSUE TITLE
io.kubernetes:client-java:3.0.0-beta1 is broken

### ISSUE THREAD

**Issue by bootstraponline** [kubernetes-client/java#328] opened 2018-07-30 18:10 UTC
`CoreV1Api` doesn't exist. 

```gradle
implementation("io.kubernetes:client-java:3.0.0-beta1")
```

**Comment by brendandburns** [comment] 2018-08-01 20:51
Duplicate of #327

**Closed** 2018-08-01 21:09 UTC
