### ISSUE TITLE
OpenidApi and WellKnownApi

### ISSUE THREAD

**Issue by balsemindevis** [kubernetes-client/java#2295] opened 2022-06-27 15:28 UTC
**Describe the bug**
OpenidApi and WellKnownApi have coded the wrongLocalPath.
    String localVarPath = "/openid/v1/jwks/";

and          String localVarPath = "/.well-known/openid-configuration/";

The last "/" generate an 403 Response. 

I have remove Last "/" in both file and works fine
 

**Client Version**
`15.0.1`

**Java Version**

Java 17

**To Reproduce**

httpStatus:403
curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/.well-known/openid-configuration/

httpStatus:200
curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/.well-known/openid-configuration

**Comment by yue9944882** [comment] 2022-06-28 05:43
@balsemindevis i cant reproduce that in my local kind cluster, is that a vendor-specific issue?

**Comment by balsemindevis** [comment] 2022-06-28 06:53
> @balsemindevis i cant reproduce that in my local kind cluster, is that a vendor-specific issue?

the same thing happens on both minikube and k8s. The "issue" can be replicate also outside client-java  because with last "/" character corrupt the request.

![image](https://user-images.githubusercontent.com/108286978/176112796-35d44bf7-4039-4ebf-b06e-8508a8a567d6.png)


![image](https://user-images.githubusercontent.com/108286978/176112977-b9d562b0-67b3-4b3a-b5e6-5b029444e211.png)

it's wrong last "/".

**Comment by yue9944882** [comment] 2022-06-29 11:30
it should be fixed in the upstream kubernetes repo, so i opened https://github.com/kubernetes/kubernetes/pull/110861. a walkaround is to add the following non-resource urls to the `ClusterRole` named "system:service-account-issuer-discovery":

```
...
rules:
- nonResourceURLs:
  - /.well-known/openid-configuration
  - /openid/v1/jwks
  - /.well-known/openid-configuration/ # ADD THESE
  - /openid/v1/jwks/                                 #
  verbs:
  - get
```

**Closed** 2022-11-26 12:31 UTC
Labels: lifecycle/rotten
