### ISSUE TITLE
ConnectGetNamespacedPodExec fails with 'Upgrade Required'

### ISSUE THREAD

**Issue by tingweiwu** [kubernetes-client/java#337] opened 2018-08-09 11:48 UTC
I'm trying to use the Java client to execute a command in a container in a pod.

coreV1Api.connectGetNamespacedPodExec(name, namespace, command, name, true, false, true, false);
     
The server returns ApiException as following:

```shell
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Upgrade request required","reason":"BadRequest","code":400}

```

could anyone help?

**Comment by tingweiwu** [comment] 2018-08-09 13:55
I saw the python client issue https://github.com/kubernetes-client/python/issues/58 
it is related with the fact that requests is not SPDY compatible.

**Comment by kondapally1989** [comment] 2018-08-09 17:13
@tingweiwu 
there is an example of how to use Exec of the jar 
https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/ExecExample.java

**Comment by brendandburns** [comment] 2018-08-10 22:31
Closing this since that example is correct. One thing to note is that if you have a proxy in the way, you need to make sure that it preserves the `Host` header.

**Closed by brendandburns** 2018-08-10 22:31 UTC

**Comment by ekovacs** [comment] 2020-02-19 19:10
basically the java-client will be scattered with broken methods like this, if such bug reports are closed :-/

**Comment by brendandburns** [comment] 2020-02-24 02:42
The problem is that the methods are documented in Swagger/OpenAPI, so the code generator blindly generates them.

But the actual protocol used for implementing the methods (WebSockets) is something that the code generator doesn't support.

In theory we could modify the code gen project (https://github.com/kubernetes-client/gen) to strip those methods out of the Swagger before we generate the code, but it seems like a lot of work for minimal pay-off.

That said, if someone wants to take this on as a project, I'd gladly merge the PR. But it needs to be a change to https://github.com/kubernetes-client/gen, not this repo.

**Comment by marceloFA** [comment] 2023-04-13 19:27
> The problem is that the methods are documented in Swagger/OpenAPI, so the code generator blindly generates them.
> 
> But the actual protocol used for implementing the methods (WebSockets) is something that the code generator doesn't support.
> 
> In theory we could modify the code gen project (https://github.com/kubernetes-client/gen) to strip those methods out of the Swagger before we generate the code, but it seems like a lot of work for minimal pay-off.
> 
> That said, if someone wants to take this on as a project, I'd gladly merge the PR. But it needs to be a change to https://github.com/kubernetes-client/gen, not this repo.

Does this mean that the method _ConnectGetNamespacedPodExec_ is in fact unusable?
