### ISSUE TITLE
io.kubernetes.client.openapi.models.V1PodBuilder can't be resolved

### ISSUE THREAD

**Issue by qtornado** [kubernetes-client/java#800] opened 2019-11-14 06:09 UTC
1、The import io.kubernetes.client.openapi.models.V1PodBuilder cannot be resolved

2、The delete api return V1Status  Object, but  it's actually a V1Namespace or V1Pod object, or even more
![image](https://user-images.githubusercontent.com/5219170/68830992-3172ae00-06e8-11ea-870d-1021c395ac6c.png)

**Comment by brendandburns** [comment] 2019-11-15 00:08
Bug 2 is a duplicate of #86 please see that for more details, the fundamental problem is that the Kubernetes API can return two different objects depending on the state of the async response.

Will take a look at reproducing 1)

**Comment by brendandburns** [comment] 2019-11-15 05:13
I can't seem to reproduce 1) at HEAD, everything compiles just fine.

Can you add some details about what you are running? What is in your pom.xml?

**Comment by qtornado** [comment] 2019-11-15 05:49
> I can't seem to reproduce 1) at HEAD, everything compiles just fine.
> 
> Can you add some details about what you are running? What is in your pom.xml?

In the code of master, there is no V1PodBuilder and V1ServiceBuilder class.
![image](https://user-images.githubusercontent.com/5219170/68919715-0a7eaf80-07ae-11ea-8c10-6b26d79f4261.png)

![image](https://user-images.githubusercontent.com/5219170/68919683-f20e9500-07ad-11ea-878b-d7e972ac93c6.png)

![image](https://user-images.githubusercontent.com/5219170/68919945-b627ff80-07ae-11ea-868f-704c1ca65212.png)

**Comment by brendandburns** [comment] 2019-11-16 01:05
That code is code-generated by the [sundrio](https://github.com/sundrio/sundrio) tool when you do a `mvn install`

Are you trying to compile the code from scratch? You should probably use the maven package instead.

**Comment by tly1980** [comment] 2019-12-04 01:04
Had a similar issues with `implementation 'io.kubernetes:client-java:5.0.0'`
And it seems those class exists in package `io.kubernetes.client.models` , in stead of `io.kubernetes.client.openapi.models` ?

**Closed** 2020-05-02 02:54 UTC
Labels: lifecycle/rotten
