### ISSUE TITLE
Socket is closed!

### ISSUE THREAD

**Issue by tiandizhiguai** [kubernetes-client/java#2196] opened 2022-04-01 11:58 UTC
WebSocketStreamHandler.close() throws the error as fallow,  I think the code : "state = State.CLOSED" should be at the end of the method.
java.io.IOException: Socket is closed!
	at io.kubernetes.client.util.WebSocketStreamHandler$WebSocketOutputStream.flush(WebSocketStreamHandler.java:221)
	at io.kubernetes.client.util.WebSocketStreamHandler.close(WebSocketStreamHandler.java:136)
	at io.kubernetes.client.Exec$ExecProcess$1.close(Exec.java:542)
	at io.kubernetes.client.Exec$ExecProcess$1.handleMessage(Exec.java:508)
	at io.kubernetes.client.util.WebSocketStreamHandler.bytesMessage(WebSocketStreamHandler.java:75)
	at io.kubernetes.client.util.WebSockets$Listener.onMessage(WebSockets.java:142)
	at okhttp3.internal.ws.RealWebSocket.onReadMessage(RealWebSocket.java:326)
	at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:221)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:105)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by brendandburns** [comment] 2022-04-03 18:28
I think this is a duplicate of https://github.com/kubernetes-client/java/issues/1891

Closing in favor of that issue. (which sadly we haven't fixed yet...)

Will try to get to it soon. Please use the `/reopen` command if you think this is a different issue.

**Closed by brendandburns** 2022-04-03 18:28 UTC

**Comment by ltamaster** [comment] 2022-04-28 21:48
I have the same issue and the other ticket was closed
