### ISSUE TITLE
Issue while copying file to newly created pod

### ISSUE THREAD

**Issue by charcharan** [kubernetes-client/java#2044] opened 2021-12-23 15:24 UTC
**Describe the bug**
Unable to copy file to Pod.
Created a simple pod, and trying to add a file and execute in Java environment

**Client Version**
`14.0.0`

**Kubernetes Version**
`1.22.4`

**Java Version**
Java 11

**To Reproduce**
Created a simple pod, and trying to add a file and execute in Java environment

**Expected behavior**
File should be moved to pod and it should be executed.

**KubeConfig**
If applicable, add a KubeConfig file with secrets redacted.

**Server (please complete the following information):**
 - OS: Windows
 - Environment - local Docker Kubernetes
 - Cloud - NA

**Additional context**
Code sample which i have tried
Creating a pod :
```
        ApiClient client = Config.defaultClient();
        Configuration.setDefaultApiClient(client);
        V1Pod pod =
                new V1Pod()
                        .metadata(new V1ObjectMeta().name("abc").namespace("default"))
                        .spec(
                                new V1PodSpec()
                                        .containers(Arrays.asList(new V1Container().name("somecontainer").image("sample-image"))));

        ApiClient apiClient = ClientBuilder.standard().build();
        GenericKubernetesApi<V1Pod, V1PodList> podClient =
                new GenericKubernetesApi<>(V1Pod.class, V1PodList.class, "", "v1", "pods", apiClient);
        PodLogs logs = new PodLogs();
        V1Pod latestPod = podClient.create(pod).throwsApiException().getObject();
        System.out.println("Created!");
```
It got created without any issues, But trying to copy file to pod,

```
        Copy copy = new Copy();
        copy.copyFileToPod("default", "abc", "somecontainer", file1.toPath(), Paths.get("/path/to/pod/"));
        System.out.println("Done!");
```

Getting this error while copying file,
```
java.net.ProtocolException: Expected HTTP 101 response but was '500 Internal Server Error'
	at okhttp3.internal.ws.RealWebSocket.checkUpgradeSuccess(RealWebSocket.java:224)
	at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:195)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)
2021-12-23 20:52:26.444 ERROR 13992 --- [ternal:6443/...] i.k.client.util.WebSocketStreamHandler   : Error on flush

java.io.IOException: Socket is closed!

```
Am I missing something ?
Can anyone help me how to proceed on resolving the issue ?

**Comment by brendandburns** [comment] 2021-12-23 23:49
This looks like a server-side 500 error. You will need to look at the kubernetes API server logs to see if you can get more details about why it is throwing a 500.

The client is trying to upgrade to a web socket and getting a 500, there's not much more the client can do here.

**Comment by charcharan** [comment] 2021-12-24 04:50
Hi Brendan, 

Thanks for the reply, I am new to k8s and in learning stage, Can you help me on how to check server logs ?
 I am using local docker kubernetes cluster.

**Comment by brendandburns** [comment] 2021-12-29 00:25
Sorry, there's really nothing more that I can do to help here. The server is throwing a 500 when we try to upgrade the websocket. Without more information about why that is happening there's no way to know what is causing the problem.

You referenced the issue where `tar` is missing. It's definitely the case that `tar` needs to be present in your container, if it's not it will cause a problem, so you should validate that `tar` is present in that container.

The 500 should be in the apiserver logs, I would try searching for `500` in those logs using `grep` or somesuch. But there's really not much more we can do without more info.

**Comment by charcharan** [comment] 2021-12-29 06:40
Hi, Thanks for the reply.

I have observed one more thing, Whenever the pod gets created and after executing the command mentioned in DockerFile, the pod status was "CrashLoopBackOff". Do this will be the reason for this ?

I haven't found any logs regarding "500 Internal server error" in kube-apiserver logs. 

Meanwhile, I will validate regarding tar whether it's present in the container.

**Comment by brendandburns** [comment] 2022-01-02 20:07
Your pod is crashing repeatedly. That is the cause for being unable to exec, your Pod isn't running correctly. You need to get your pod running successfully (state is `Running`) before you can expect that exec-ing into that pod should work.

Closing this issue since it is definitely not a problem with this client.

**Closed by brendandburns** 2022-01-02 20:07 UTC
