### ISSUE TITLE
Compilation errors in Sprint Tool Suite

### ISSUE THREAD

**Issue by nareshadoni1** [kubernetes-client/java#1196] opened 2020-08-26 22:08 UTC
Facing a problem using Open JDK 11 (latest openjdk-11+28_windows-x64_bin.zip) and Spring Tool Suite.  Cleared local maven repo and built clean and updated project but cannot seem to work around the following error with latest code checked in as of today. From commandline with Mvn it seemed to not encounter this and has compiled. 
Description	Resource	Path	Location	Type
The method submit(Callable<Object>) is ambiguous for the type ExecutorService	SharedInformerFactory.java	/util/src/main/java/io/kubernetes/client/informer	line 249	Java Problem
The type of run() from the type SharedInformer is void, this is incompatible with the descriptor's return type: Object	SharedInformerFactory.java	/util/src/main/java/io/kubernetes/client/informer	line 249	Java Problem

Description	Resource	Path	Location	Type
The method submit(Callable<Object>) is ambiguous for the type ExecutorService	SharedInformerFactory.java	/util/src/main/java/io/kubernetes/client/informer	line 249	Java Problem
The type of run() from the type SharedInformer is void, this is incompatible with the descriptor's return type: Object	SharedInformerFactory.java	/util/src/main/java/io/kubernetes/client/informer	line 249	Java Problem

**Comment by brendandburns** [comment] 2020-08-27 23:37
Given that it builds on your command line using `mvn` this seems like a problem in the spring tool suite rather than in the project. The supported/tested way to build is `maven`

I'm not sure any of the current developers use that toolchain, but if you figure out the problem, we'd be happy to take a PR with the fix.

**Comment by brendandburns** [comment] 2020-09-18 18:35
Closing this issue since no further action seems possible.

**Closed by brendandburns** 2020-09-18 18:35 UTC

**Comment by dsyer** [comment] 2020-11-30 15:25
I'm pretty sure the problem is nothing to do with the IDE. If you build this project with Java 11 and then run an app that uses it with Java 8 you will see the same result (the fix is to use Java 8 for both). Hope that helps someone.

**Comment by dsyer** [comment] 2020-12-07 14:43
Another possibility is that it is a JDT bug/quirk (so it affects all Eclipse and VSCode users). The fix is trivial in that case - just cast the method reference to `Runnable`.
