### ISSUE TITLE
Unable to replace/patch the service or pdb

### ISSUE THREAD

**Issue by sandeeprajub4u** [kubernetes-client/java#550] opened 2019-04-09 05:00 UTC
We are getting below error when we try to use replaceNamespacedServiceCall or replaceNamespacedService or patchNamespacedServiceCall or patchNamespacedService in CoreV1Api.
Response{protocol=http/1.1, code=422, message=Unprocessable Entity, url=https://k8s-cluster.test.com:6443/api/v1/namespaces/mynamespace/services/myservice}

We are seeing the similar issue with pdb and we are using PolicyV1beta1Api

**Comment by yue9944882** [comment] 2019-04-10 04:18
sounds like separated issues. for `replaceNamespacedServiceCall ` calls, 422 suggests that the posted service fails the api validation. `patchNamespacedService` can by caused by illegal patch formats which can be a duplicate of #127

**Comment by brendandburns** [comment] 2019-04-26 03:51
Closing this in favor of #127 or possibly just because it's a malformed request.

**Closed by brendandburns** 2019-04-26 03:51 UTC
