### ISSUE TITLE
Deleting Namespaced Persistent Volume Claim throws IllegalStateException but the PVC is deleted

### ISSUE THREAD

**Issue by PhaniKumar** [kubernetes-client/java#948] opened 2020-05-11 11:17 UTC
**IllegalStateException is thrown when deleting  the PVC but the PVC is deleted**

**Client Version: 7.0.0**
**Server Version 1.15.7**

``` java
ApiClient client = ClientBuilder.cluster().build();
Configuration.setDefaultApiClient(client);
CoreV1Api api = new CoreV1Api();
api.deleteNamespacedPersistentVolumeClaim(claimName, K8Config.getNamespace(), null, null, null, null, null, null);
```

Exception
``` log
Exception[java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 801 path $.status]
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 801 path $.status
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:226)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:139)
        at io.kubernetes.client.openapi.ApiClient.deserialize(ApiClient.java:765)
        at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:968)
        at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:895)
        at io.kubernetes.client.openapi.apis.CoreV1Api.deleteNamespacedPersistentVolumeClaimWithHttpInfo(CoreV1Api.java:13365)
        at io.kubernetes.client.openapi.apis.CoreV1Api.deleteNamespacedPersistentVolumeClaim(CoreV1Api.java:13337

```

**Comment by brendandburns** [comment] 2020-05-11 17:58
This is a duplicate of #86 please see details in that issue.

Closing as duplicate.

**Closed by brendandburns** 2020-05-11 17:58 UTC
