### ISSUE TITLE
Pod CPU usage in %

### ISSUE THREAD

**Issue by bhargaviaaa** [kubernetes-client/java#860] opened 2020-02-11 06:05 UTC
How to get Pod CPU usage in %. Also which api and method to be used for kubectl top pods?

**Comment by brendandburns** [comment] 2020-02-11 19:45
This is a duplicate of #717 please take a look at the solution there.

tl; dr; `kubectl top ...` is not a single API call, but rather code in the `kubectl` binary. You will need to duplicate the code in this library. We'd be happy to take a PR to add this functionality if you write it.

**Closed by brendandburns** 2020-02-11 19:45 UTC
