### ISSUE TITLE
return value json parsing error : CoreV1Api.deleteNamespacedPersistentVolumeClaim 

### ISSUE THREAD

**Issue by cwchoe** [kubernetes-client/java#1206] opened 2020-08-31 02:54 UTC
I got an error when i call CoreV1Api.deleteNamespacedPersistentVolumeClaim.

- kubernetes java client version: 9.0.2
- Gson version: gson-2.8.6.jar
- Details: 

[ERROR] [31] 2020-08-31 11:47:25.893 |http-nio-8080-exec-2|ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet]|[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 820 path $.status] with root cause
java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 820 path $.status
	at com.google.gson.stream.JsonReader.nextString(JsonReader.java:826) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:402) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.TypeAdapters$16.read(TypeAdapters.java:390) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[gson-2.8.6.jar:?]
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:932) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:897) ~[gson-2.8.6.jar:?]
	at com.google.gson.Gson.fromJson(Gson.java:846) ~[gson-2.8.6.jar:?]
	at io.kubernetes.client.openapi.JSON.deserialize(JSON.java:138) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.ApiClient.deserialize(ApiClient.java:757) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:958) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:883) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.apis.CoreV1Api.deleteNamespacedPersistentVolumeClaimWithHttpInfo(CoreV1Api.java:21561) ~[client-java-api-9.0.2.jar:?]
	at io.kubernetes.client.openapi.apis.CoreV1Api.deleteNamespacedPersistentVolumeClaim(CoreV1Api.java:21491) ~[client-java-api-9.0.2.jar:?]
	at com.skhynix.aip.foundation.wfmanager.taskmgr.runner.PersistentVolumeClaim.deleteObject(PersistentVolumeClaim.java:197) ~[classes/:?]
	at com.skhynix.aip.foundation.wfmanager.taskmgr.service.TaskDeployServiceImpl.deletePersistentVolumeClaim(TaskDeployServiceImpl.java:297) ~[classes/:?]
	at com.skhynix.aip.foundation.wfmanager.taskmgr.controller.TaskDeployController.deletePersistentVolumeClaim(TaskDeployController.java:103) ~[classes/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_181]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_181]
	at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1427) ~[springloaded-1.2.8.RELEASE.jar:1.2.8.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138) ~[spring-web-5.2.1.RELEASE.jar:5.2.1.RELEASE]

**Comment by yue9944882** [comment] 2020-08-31 08:24
this is a duplicate of https://github.com/kubernetes-client/java/issues/86

**Comment by brendandburns** [comment] 2020-08-31 13:56
Closing since this is a duplicate. tl;dr; the way that Kubernetes deletes objects can return multiple types, but the Swagger spec for the API only defines one.

**Closed by brendandburns** 2020-08-31 13:56 UTC
