### ISSUE TITLE
streamNamespacedPodLog closing InputStream throws "Unbalanced enter/exit" exception

### ISSUE THREAD

**Issue by conblem** [kubernetes-client/java#529] opened 2019-03-17 20:13 UTC
When I use streamNamespacedPodLog and close the InputStream I get the following Exception:
```
java.lang.IllegalStateException: Unbalanced enter/exit
	at okio.AsyncTimeout.enter(AsyncTimeout.java:62)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:451)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:435)
	at com.squareup.okhttp.internal.Util.skipAll(Util.java:159)
	at com.squareup.okhttp.internal.Util.discard(Util.java:141)
	at com.squareup.okhttp.internal.http.Http1xStream$ChunkedSource.close(Http1xStream.java:472)
	at okio.RealBufferedSource.close(RealBufferedSource.java:396)
	at okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
	at com.squareup.okhttp.internal.Util.closeQuietly(Util.java:71)
	at me.conblem.mcboss.MainVerticle.start(MainVerticle.kt:58)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$8(DeploymentManager.java:494)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:462)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

Also reading from the stream blocks indefinitely.

I am using the following versions:
```
 <dependency>
      <groupId>io.kubernetes</groupId>
      <artifactId>client-java</artifactId>
      <version>4.0.0</version>
      <scope>compile</scope>
    </dependency>
```
AdoptOpenJDK 11.0.2
Windows 10 Pro
minikube version: v0.35.0

**Comment by brendandburns** [comment] 2019-03-18 15:24
Have a look at this:

https://github.com/square/okhttp/issues/1842#issuecomment-138401070

Closing since this appears to be working as intended per okhttp...

**Closed by brendandburns** 2019-03-18 15:24 UTC

**Comment by conblem** [comment] 2019-03-19 12:15
@brendanburns Worked like a charm! Thanks alot
