### ISSUE TITLE
Adding a Wrapper class for batch processing

### ISSUE THREAD

**Issue by pianorange** [kubernetes-client/java#216] opened 2018-03-21 12:37 UTC
Hello I am a Java developer working in Tokyo.
First, thank you for providing the JavaAPI so I can use the fantastic tool called Kubernetes.

the means of wrapper class what I said is any class which "wraps" or "encapsulates" the functionality of V1Job, V1beta1CronJob class.

if someone wants to create batch processing through the Kubanetes API, I think Job and CronJob are mostly used together.
However Java has a static type system, And It has only one return type in method even if It uses generic.

 However, if WrapperClass is provided, it can wrap V1Job and V1beta1CronJob. It will be helpful for developers to write more flexile code and improve type readability.  

1. for example, when I use generic type for returning V1Job, V1beta1CronJob 
 >
    public <R> R convertJobDefinition(String jobDefinitionStr) throws IOException, InvalidValueException {
            R result = null;
            ObjectMapper objectMapper = new ObjectMapper();
            V1Job jobObject = objectMapper.readValue(jobDefinitionStr, V1Job.class);

           if(jobObject != null){
                result = (R) jobObject;

            }else if (jobObject == null){
                 V1beta1CronJob cronJobObject = objectMapper.readValue(jobDefinitionStr, V1beta1CronJob.class);
            if (cronJobObject != null){
                 result = (R) cronJobObject;
            } else {
                 throw new InvalidValueException();
            }
        return result;
     }
>

2. In this case, programmer have to write typeCheck(some predicate instanceof, getClass() etc,,) to know what kind of type returned.
>
      Object result = testclass.convertJobDefinition("jobDefinitionStr");
      if(result instanceof V1Job){
              
      }else if (result instanceof V1beta1CronJob){

      }
>

3. However, if WrapperClass is provided, it can wrap V1Job and V1beta1CronJob. It will be helpful for developers to write more flexile code.

>
    public class V1Job  extends V1JobObject {
    public class V1beta1CronJob extends V1JobObject {
    public V1JobObject convertJobDefinition(String jobDefinitionStr) throws IOException, InvalidValueException

    V1JobObject result = testclass.convertJobDefinition("jobDefinitionStr");
          
     if(result instanceof V1Job){
              
     }else if (result instanceof V1beta1CronJob){

      }
>

**Comment by brendandburns** [comment] 2018-03-22 04:13
Thanks for filing the detailed issue.

I think this is a duplicate of #101

And sadly, we can't handle it currently because our code generator doesn't support parent classes.

As soon as it does, then we will definitely do this.

I'm going to close this issue in favor of #101, please re-open if I missed something.

Thanks!

**Closed by brendandburns** 2018-03-22 04:13 UTC
