### ISSUE TITLE
Failed with JsonSyntaxException during deleteNamespacedPod 

### ISSUE THREAD

**Issue by Jinchul81** [kubernetes-client/java#230] opened 2018-04-03 02:07 UTC
My system is built based on Kubernetes v1.9, client-java-parent-1.0.0-beta3
Unexpected exception occurred while running  deleteNamespacedPod. I think the root cause is inconsistency between actual object and expected object. Let's see the problem. The function's return type is V1Status. V1Status.status is String type, but Kubernetes responds a struct type (i.e. V1PodStatus). It seems V1Status.status can be a template type which can be V1PodStatus, V1beta2StatefulSetStatus and so on.

My initial idea is V1Status should take a template class for the inner status when its instantiation.

**Comment by brendandburns** [comment] 2018-04-03 04:14
Duplicate of #86  (and still no good solution...)

**Closed by brendandburns** 2018-04-03 04:14 UTC
