### ISSUE TITLE
Delete job fails to deserialize response

### ISSUE THREAD

**Issue by tomzo** [kubernetes-client/java#363] opened 2018-09-09 15:14 UTC
When deleting a job with code like this:
```
V1DeleteOptions deleteOptions = new V1DeleteOptions();
        String propagationPolicy = "Foreground";
        deleteOptions.setPropagationPolicy(propagationPolicy);
        batchV1Api.deleteNamespacedJob(jobName, namespace, deleteOptions, "false", 0, null, propagationPolicy);
```

The request is accepted by k8s api and it is processed. But then client fails to deserialize response and throws following exception:
```
com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column 1220 path $.status

	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:879)
	at com.google.gson.Gson.fromJson(Gson.java:844)
	at com.google.gson.Gson.fromJson(Gson.java:793)
	at io.kubernetes.client.JSON.deserialize(JSON.java:110)
	at io.kubernetes.client.ApiClient.deserialize(ApiClient.java:668)
	at io.kubernetes.client.ApiClient.handleResponse(ApiClient.java:871)
	at io.kubernetes.client.ApiClient.execute(ApiClient.java:798)
	at io.kubernetes.client.apis.BatchV1Api.deleteNamespacedJobWithHttpInfo(BatchV1Api.java:511)
	at io.kubernetes.client.apis.BatchV1Api.deleteNamespacedJob(BatchV1Api.java:491)
```

This is failing in `2.0.0` and `3.0.0-beta2` versions of java client.
K8s version 1.10

**Comment by tomzo** [comment] 2018-09-09 15:32
Related cause on server side - https://github.com/kubernetes/kubernetes/issues/65121

**Comment by brendandburns** [comment] 2018-09-10 02:50
Yeah, known issue... Dupe of #86, closing.

**Closed by brendandburns** 2018-09-10 02:50 UTC
