### ISSUE TITLE
Watch Error(Warning: A connection to <IP> was leaked...)

### ISSUE THREAD

**Issue by bluechips23** [kubernetes-client/java#278] opened 2018-05-25 17:32 UTC
I have a very simple Watch on Pods. Here's the code:

```
Watch<V1Pod> watch = Watch.createWatch(
                    apiClient,
                    api.listPodForAllNamespacesCall(null, null, null, null,
                            null, null, null, null, true, null, null),
                    new TypeToken<Watch.Response<V1Pod>>() {}.getType());

            watch.forEach( response  -> {
                V1Pod pod = response.object;
                Map<String, String> labels = pod.getMetadata().getLabels();
                String appName = labels == null ? "" : labels.getOrDefault("app", "");
                String status = pod.getStatus().getPhase();
                if ( !appName.isEmpty() )
                    System.out.printf("App %s, Status %s%n", appName, status);
            });
```

Issue: When I make this call, I get a list of all the pods but after a while I'm getting this error:

`WARNING: A connection to [IP_ADDRESS] was leaked. Did you forget to close a response body?`

How do I catch this error? What's the best way to handle this error?

**Comment by brendandburns** [comment] 2018-05-26 03:46
This is a duplicate of #269 It looks like a bug in the library's watch code. I haven't had a chance to track it down yet... (apologies)

**Closed by brendandburns** 2018-05-26 03:46 UTC
