### ISSUE TITLE
Any plan to support k8s v1.17 and v1.18?

### ISSUE THREAD

**Issue by tangzhankun** [kubernetes-client/java#1064] opened 2020-07-14 03:45 UTC
As the title mentioned, could anyone help to clarify the roadmap? Thanks a lot!

**Comment by brendandburns** [comment] 2020-07-14 17:03
Yes, this is a duplicate of #1050 

The code in HEAD is currently 1.17, note that the library should mostly work with 1.17 and 1.18 but obviously it won't support new APIs.

I will cut a new release and re-generate for 1.18 this week.

**Comment by goods4455** [comment] 2020-07-20 05:12
I really waiting for new release

**Comment by outi85** [comment] 2020-07-20 11:03
Same here, I'm also waiting!

**Comment by yue9944882** [comment] 2020-07-21 11:27
@brendandburns anything we missed before our 1.17 release takes off?

**Comment by allupaku** [comment] 2020-07-27 13:20
👍 waiting for this ..

**Comment by yue9944882** [comment] 2020-07-27 15:57
@allupaku 1.17 (v9.0.0) is already out

**Comment by isliqian** [comment] 2020-08-24 03:04
Same here, I'm also waiting!

**Comment by brendandburns** [comment] 2020-09-18 18:42
Closing this as both `9.0.x` and `10.0.0` have been released.

**Closed by brendandburns** 2020-09-18 18:42 UTC
