### ISSUE TITLE
deleteNamespacedJob throws 'com.google.gson.JsonSyntaxException' exception.

### ISSUE THREAD

**Issue by alextarasov-spot** [kubernetes-client/java#1484] opened 2021-01-07 14:22 UTC
I'm using `BatchV1Api.deleteNamespacedJob` method. This method returns `V1Status` object, the K8s OpenApi specifications says the same - the DELETE method of the `/apis/batch/v1/namespaces/{namespace}/jobs/{name}`  API route returns `io.k8s.apimachinery.pkg.apis.meta.v1.Status` ([K8s OpenAPI swagger](https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json)) 

When the `deleteNamespacedJob` method receives a response from the k8s API it, unexpectedly, receives a `V1Job` object:

![image](https://user-images.githubusercontent.com/54230036/103902281-f3fa8c80-5102-11eb-8201-2ebdfa0c169d.png)

and then it tries to deserialize the `V1Job` to the `V1Status` and fails with the 'com.google.gson.JsonSyntaxException' exception.

https://github.com/kubernetes-client/java/blob/6267ff3cb7ad12984bd1a9aec96ee3b075da460b/kubernetes/src/main/java/io/kubernetes/client/openapi/ApiClient.java#L759

**Comment by brendandburns** [comment] 2021-01-07 16:35
Please see the discussion in #86 

This should be fixed at HEAD and will be part of the next (12.0.0) release.

**Comment by brendandburns** [comment] 2021-01-07 16:35
Closing since this is a duplicate of #86

**Closed by brendandburns** 2021-01-07 16:35 UTC
