### ISSUE TITLE
how can i rollout using java-sdk,just simulating like `kubectl rollout`

### ISSUE THREAD

**Issue by zhamdoctor** [kubernetes-client/java#1175] opened 2020-08-20 08:00 UTC
how can i simulate actions like `kubectl rollout history` or `kubectl rollout undo` etc.  I found neither  the right interfaces nor resources to simulate actions like above. I just find resources like `controllerrevision` `ExtensionsV1beta1DeploymentRollback`,but I do not know how to use them making them acting like `kubectl rollout`. also, ExtensionsV1beta1DeploymentRollback was marked deprecated. Please give me some example. oh, finally,I follow the openapi `https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.18` but failed when rolling out

**Comment by brendandburns** [comment] 2020-08-26 04:50
rollout is a pretty complicated command, it's not a simple API call.

#1072 is an umbrella issue covering kubectl equivalents and we'll eventually get to `rollout`

I'm going to close this issue since it's a duplicate of #1072

**Closed by brendandburns** 2020-08-26 04:50 UTC
