### ISSUE TITLE
JSON parsing exception in BatchV1Api.deleteNamespacedJob()

### ISSUE THREAD

**Issue by opottone** [kubernetes-client/java#253] opened 2018-04-26 23:24 UTC
When I call `BatchV1Api.deleteNamespacedJob()`, it throws an `java.lang.IllegalStateException`. It succesfully makes a REST call to the Kubernetes server, gets a response, and tries to parse the response json to a `V1Status` object. This fails. When I modified the client to use `V1Job` instead of `V1Status`, then it works.

The exception gets thrown because `status` field in `V1Status` is a `String`, but in response json it's an object:
```
"status": {
        "conditions": [
            {
                "type": "Complete",
                "status": "True",
                "lastProbeTime": "2018-04-26T22:16:28Z",
                "lastTransitionTime": "2018-04-26T22:16:28Z"
            }
        ],
        "startTime": "2018-04-26T22:16:18Z",
        "completionTime": "2018-04-26T22:16:28Z",
        "succeeded": 1
    }
```
It's quite possible there are also other differences between  `V1Status` and `V1Job` but I didn't bother to investigate further.

**Comment by brendandburns** [comment] 2018-04-27 04:31
Duplicate of #86

**Closed by brendandburns** 2018-04-27 04:31 UTC
