### ISSUE TITLE
Generated CRD model classes don't have the value of Kind, ApiVersion

### ISSUE THREAD

**Issue by SayakMukhopadhyay** [kubernetes-client/java#2337] opened 2022-08-10 11:09 UTC
**Describe the bug**
When generating java model classes from my own CRDs using the documentation [here](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md#example-commands-for-local-crd-manifests), the resultant Java classes have the fields for `kind` and `apiVersion` but those fields don't have a value set. This is troublesome cause if I need to generate a resource from those classes, I have to repeatedly set the values for those fields. Moreover, this information was not given in the above documentation.

**Client Version**
`16.0.0`

**Kubernetes Version**
`1.23.1`

**Java Version**
Java 17

**To Reproduce**
1. Have a CRD handy.
2. Generate the java classes for the CRD using the directions given [here](https://github.com/kubernetes-client/java/blob/master/docs/generate-model-from-third-party-resources.md#example-commands-for-local-crd-manifests).
```java
/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package my.test.kubernetes.models;

import java.util.Objects;
import java.util.Arrays;
import my.test.kubernetes.models.V1alpha1TestStuffSpec;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.kubernetes.client.openapi.models.V1ObjectMeta;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TestStuff is the Schema for the TestStuffs API
 */
@ApiModel(description = "TestStuff is the Schema for the TestStuffs API")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-08-06T12:09:16.814Z[Etc/UTC]")
public class V1alpha1TestStuff implements io.kubernetes.client.common.KubernetesObject {
  public static final String SERIALIZED_NAME_API_VERSION = "apiVersion";
  @SerializedName(SERIALIZED_NAME_API_VERSION)
  private String apiVersion;

  public static final String SERIALIZED_NAME_KIND = "kind";
  @SerializedName(SERIALIZED_NAME_KIND)
  private String kind;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private V1ObjectMeta metadata = null;

  public static final String SERIALIZED_NAME_SPEC = "spec";
  @SerializedName(SERIALIZED_NAME_SPEC)
  private V1alpha1TestStuffSpec spec;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private Object status;


  public V1alpha1TestStuff apiVersion(String apiVersion) {
    
    this.apiVersion = apiVersion;
    return this;
  }

   /**
   * APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
   * @return apiVersion
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources")

  public String getApiVersion() {
    return apiVersion;
  }


  public void setApiVersion(String apiVersion) {
    this.apiVersion = apiVersion;
  }


  public V1alpha1TestStuff kind(String kind) {
    
    this.kind = kind;
    return this;
  }

   /**
   * Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
   * @return kind
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds")

  public String getKind() {
    return kind;
  }


  public void setKind(String kind) {
    this.kind = kind;
  }


  public V1alpha1TestStuff metadata(V1ObjectMeta metadata) {
    
    this.metadata = metadata;
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1ObjectMeta getMetadata() {
    return metadata;
  }


  public void setMetadata(V1ObjectMeta metadata) {
    this.metadata = metadata;
  }


  public V1alpha1TestStuff spec(V1alpha1TestStuffSpec spec) {
    
    this.spec = spec;
    return this;
  }

   /**
   * Get spec
   * @return spec
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1alpha1TestStuffSpec getSpec() {
    return spec;
  }


  public void setSpec(V1alpha1TestStuffSpec spec) {
    this.spec = spec;
  }


  public V1alpha1TestStuff status(Object status) {
    
    this.status = status;
    return this;
  }

   /**
   * TestStuffStatus defines the observed state of TestStuff
   * @return status
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "TestStuffStatus defines the observed state of TestStuff")

  public Object getStatus() {
    return status;
  }


  public void setStatus(Object status) {
    this.status = status;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1alpha1TestStuff v1alpha1TestStuff = (V1alpha1TestStuff) o;
    return Objects.equals(this.apiVersion, v1alpha1TestStuff.apiVersion) &&
        Objects.equals(this.kind, v1alpha1TestStuff.kind) &&
        Objects.equals(this.metadata, v1alpha1TestStuff.metadata) &&
        Objects.equals(this.spec, v1alpha1TestStuff.spec) &&
        Objects.equals(this.status, v1alpha1TestStuff.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(apiVersion, kind, metadata, spec, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1alpha1TestStuff {\n");
    sb.append("    apiVersion: ").append(toIndentedString(apiVersion)).append("\n");
    sb.append("    kind: ").append(toIndentedString(kind)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    spec: ").append(toIndentedString(spec)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
```
3.  Try to create Custom Resource Object for the CRD
```java
V1alpha1TestStuff testStuff = new V1alpha1TestStuff()
    .metadata(
        new V1ObjectMeta()
            .name("test")
            .namespace("default")
    )
    .spec(
        new V1alpha1TestStuffSpec()
            .name("test")
    );
this.customObjectsApi.createNamespacedCustomObject(
    "my.test",
    "v1alpha1",
    "default",
    "testStuffs",
    testStuff,
    "true",
    null,
    this.FIELD_MANAGER
);
```                
4. This gives an error as follows
```
Exception in thread "main" io.kubernetes.client.openapi.ApiException: 
	at io.kubernetes.client.openapi.ApiClient.handleResponse(ApiClient.java:973)
	at io.kubernetes.client.openapi.ApiClient.execute(ApiClient.java:885)
	at io.kubernetes.client.openapi.apis.CustomObjectsApi.createNamespacedCustomObjectWithHttpInfo(CustomObjectsApi.java:535)
	at io.kubernetes.client.openapi.apis.CustomObjectsApi.createNamespacedCustomObject(CustomObjectsApi.java:490)
	at my.test.kubernetes.TestStuff.createTestStuff(TestStuff.java:53)
	at my.test.kafka.ExecutionConsumer.handleRecords(ExecutionConsumer.java:68)
	at my.test.kafka.ExecutionConsumer.consume(ExecutionConsumer.java:60)
	at my.test.Main.main(Main.java:16)
```
5. An on inspecting the error, I see this API error returned to the ApiClient
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "TestStuff in version \"v1alpha1\" cannot be handled as a TestStuff: Object 'Kind' is missing in '{\"metadata\":{\"name\":\"test\",\"namespace\":\"default\"},\"spec\":{\"name\":\"test\"}}'",
  "reason": "BadRequest",
  "code": 400
}
```
6. The resource is successfully created if I set the Kind and ApiVersion manually
```java
V1alpha1TestStuff testStuff = new V1alpha1TestStuff()
    .kind("testStuffs")
    .apiVersion("my.test/v1alpha1")
    .metadata(
        new V1ObjectMeta()
            .name("test")
            .namespace("default")
    )
    .spec(
        new V1alpha1TestStuffSpec()
            .name("test")
    );
````

**Expected behavior**
I expected the Kind and ApiVersion to be assigned by default in the model class since each model class is for a single Kind and ApiVersion, the class name reflects that.

**KubeConfig**
NA

**Server (please complete the following information):**
 - OS: Minikube on Windows 11
 - Environment: Minikube
 - Cloud: No

**Additional context**
I am inclined to believe that it is more of an issue for https://github.com/kubernetes-client/gen than this repo but putting this here since I am unsure about that.

**Comment by brendandburns** [comment] 2022-08-11 17:27
None of the Java objects have static values for apiVersion or kind.

(e.g. https://github.com/kubernetes-client/java/blob/master/kubernetes/src/main/java/io/kubernetes/client/openapi/models/V1Pod.java)

OpenAPI 3 has some notion of 'default' values but I do not believe they are in the Kubernetes OpenAPI specification, and I'm not sure if the code generator even supports them (and we currently use an OpenAPI 2 generator anyway)

I'm going to close this as "working as intended" because there's no near-term path forward (and indeed if there is to be a path it is going to require lots of changes in other repos).

**Closed by brendandburns** 2022-08-11 17:27 UTC
