### ISSUE TITLE
Call the delete method to prompt for an exception

### ISSUE THREAD

**Issue by kangtutu** [kubernetes-client/java#823] opened 2019-12-05 03:10 UTC
In the use of API calls deleteNamespacedReplicaSet method, the underlying encapsulation times wrong in the response result parameters, prompt [Java. Lang. An IllegalStateException: Expected a string but was BEGIN_OBJECT at line 1 column path at $1058. The status].
My own solution for: call deleteNamespacedReplicaSetCall method, manual to respond the result of value judgment.

**Comment by brendandburns** [comment] 2019-12-05 19:28
This is a duplicate of #86 there's a discussion of the work-arounds for this issue there.

Closing because this is a duplicate.

**Closed by brendandburns** 2019-12-05 19:28 UTC
